import { useState, type ReactNode } from "react";
import { Building2, CalendarDays, ClipboardCheck, HardHat, UsersRound, WalletCards } from "lucide-react";
import {
  EmptyState, ErrorState, PageHeader, PageSkeleton, PrimaryButton, StatusBadge, SurfaceCard, fieldClass, labelClass,
} from "@/components/EquiVistaUI";
import { useAuth } from "@/contexts/AuthContext";
import { useAcademyOperationsAccess, useAcademyOperationsActions, useAcademyOperationsWorkspace } from "@/hooks/use-academy-operations";
import { useTranslation } from "react-i18next";

const localTime = (value: string, locale: string) => value ? new Date(value).toLocaleString(locale) : "—";
const toIso = (value: FormDataEntryValue | null) => new Date(String(value)).toISOString();

function Panel({ title, icon: Icon, children }: { title: string; icon: typeof UsersRound; children: ReactNode }) {
  return <SurfaceCard className="overflow-hidden">
    <div className="flex items-center gap-3 border-b border-cream-200 bg-cream-50 px-5 py-4">
      <span className="flex size-9 items-center justify-center rounded-full bg-primary-100 text-primary-700"><Icon className="size-4" aria-hidden="true" /></span>
      <h2 className="font-serif text-xl text-espresso">{title}</h2>
    </div>
    <div className="p-5">{children}</div>
  </SurfaceCard>;
}

export default function AcademyOperationsPage() {
  const access = useAcademyOperationsAccess();
  const workspace = useAcademyOperationsWorkspace();
  const actions = useAcademyOperationsActions(workspace.refetch);
  const { hasRole } = useAuth();
  const { t, i18n } = useTranslation();
  const locale = (i18n.resolvedLanguage ?? i18n.language) === "ar" ? "ar-JO" : "en-US";
  const [message, setMessage] = useState<string | null>(null);

  if (access.loading || workspace.loading) return <PageSkeleton />;
  if (access.error) return <ErrorState message={access.error} />;
  if (!access.data?.enabled || !access.data.canManage) {
    return <EmptyState icon={Building2} title={t("academyOperations.disabledTitle")} description={t("academyOperations.disabledDescription")} />;
  }
  if (workspace.error || !workspace.data) return <ErrorState message={workspace.error ?? "Academy operations are unavailable."} />;
  const data = workspace.data;
  const canApproveCompensation = hasRole("academy_admin") || hasRole("platform_admin");
  const metrics: Array<{ label: string; value: number; icon: typeof UsersRound }> = [
    { label: t("academyOperations.metrics.activeStaff"), value: data.staffProfiles.filter((staff) => staff.active).length, icon: UsersRound },
    { label: t("academyOperations.metrics.upcomingShifts"), value: data.shifts.filter((shift) => shift.status !== "cancelled" && new Date(shift.ends_at).getTime() >= Date.now()).length, icon: CalendarDays },
    { label: t("academyOperations.metrics.resourceBookings"), value: data.bookings.filter((booking) => booking.status !== "cancelled").length, icon: Building2 },
    { label: t("academyOperations.metrics.openAlerts"), value: data.alerts.filter((alert) => alert.status !== "resolved").length, icon: ClipboardCheck },
  ];
  const submit = async (fn: () => Promise<unknown>, success: string) => {
    setMessage(null);
      try { await fn(); setMessage(success); } catch { /* surfaced below */ }
  };

  return <div className="space-y-6">
    <PageHeader eyebrow={t("academyOperations.eyebrow")} title={t("academyOperations.title")} description={t("academyOperations.description")} />
    {message ? <div role="status" className="rounded-xl border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-800">{message}</div> : null}
    {actions.error ? <ErrorState message={actions.error} /> : null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {metrics.map(({ label, value, icon: Icon }) => <SurfaceCard key={label} className="p-5">
        <div className="flex items-center justify-between"><span className="text-sm font-semibold text-text-secondary">{label}</span><Icon className="size-5 text-primary-600" /></div>
        <p className="mt-3 font-serif text-3xl text-espresso">{value}</p>
      </SurfaceCard>)}
    </div>

    <div className="grid gap-6 xl:grid-cols-2">
      <Panel title={t("academyOperations.panels.staff")} icon={UsersRound}>
        <form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => {
          event.preventDefault(); const form = new FormData(event.currentTarget);
          void submit(() => actions.saveStaffProfile({
            p_staff_profile_id: null, p_user_id: form.get("userId"), p_staff_type: form.get("type"),
            p_display_name_en: form.get("nameEn"), p_display_name_ar: form.get("nameAr"), p_active: true, p_private_note: null,
          }), t("academyOperations.success.staff"));
        }}>
          <label className={labelClass}>{t("academyOperations.staff.userId")}<input required name="userId" className={fieldClass} placeholder={t("academyOperations.staff.userIdPlaceholder")} /></label>
          <label className={labelClass}>{t("academyOperations.staff.role")}<select name="type" className={fieldClass}><option value="coach">{t("academyOperations.staff.roles.coach")}</option><option value="instructor">{t("academyOperations.staff.roles.instructor")}</option><option value="yard_staff">{t("academyOperations.staff.roles.yardStaff")}</option><option value="facility_staff">{t("academyOperations.staff.roles.facilityStaff")}</option></select></label>
          <label className={labelClass}>{t("academyOperations.staff.englishName")}<input required name="nameEn" className={fieldClass} /></label>
          <label className={labelClass}>{t("academyOperations.staff.arabicName")}<input required dir="rtl" name="nameAr" className={fieldClass} /></label>
          <PrimaryButton type="submit" disabled={actions.saving} className="md:col-span-2">{t("academyOperations.staff.add")}</PrimaryButton>
        </form>
        <div className="mt-5 space-y-2">{data.staffProfiles.length ? data.staffProfiles.slice(0, 6).map((staff) => <div key={staff.id} className="flex items-center justify-between rounded-lg border border-cream-200 px-3 py-2 text-sm"><span>{staff.display_name_en} <span dir="rtl">· {staff.display_name_ar}</span></span><StatusBadge status={staff.active ? "active" : "archived"} label={t(`academyOperations.staff.statuses.${staff.active ? "active" : "archived"}`)} /></div>) : <p className="rounded-lg border border-dashed border-cream-300 bg-cream-50 px-3 py-4 text-sm text-text-secondary">{t("academyOperations.staff.none")}</p>}</div>
        <details className="mt-5 rounded-xl border border-cream-200 p-4"><summary className="cursor-pointer font-semibold text-espresso">{t("academyOperations.staff.details")}</summary>
          <div className="mt-4 grid gap-5 lg:grid-cols-2">
             <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveAvailability({ p_availability_id: null, p_staff_profile_id: form.get("staff"), p_availability_state: form.get("state"), p_starts_at: toIso(form.get("starts")), p_ends_at: toIso(form.get("ends")), p_note_en: form.get("noteEn"), p_note_ar: form.get("noteAr") }), t("academyOperations.success.availability")); }}>
               <p className="font-semibold text-sm">{t("academyOperations.availability.title")}</p><input required aria-label={t("academyOperations.availability.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.availability.staffId")} /><select aria-label={t("academyOperations.availability.state")} name="state" className={fieldClass}><option value="available">{t("academyOperations.availability.states.available")}</option><option value="limited">{t("academyOperations.availability.states.limited")}</option><option value="unavailable">{t("academyOperations.availability.states.unavailable")}</option></select><input required aria-label={t("academyOperations.availability.starts")} name="starts" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.availability.ends")} name="ends" type="datetime-local" className={fieldClass} /><input aria-label={t("academyOperations.availability.noteEnglish")} name="noteEn" className={fieldClass} placeholder={t("academyOperations.availability.noteEnglish")} /><input aria-label={t("academyOperations.availability.noteArabic")} dir="rtl" name="noteAr" className={fieldClass} placeholder={t("academyOperations.availability.noteArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.availability.save")}</PrimaryButton>
            </form>
             <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveShift({ p_shift_id: null, p_staff_profile_id: form.get("staff"), p_status: "scheduled", p_starts_at: toIso(form.get("starts")), p_ends_at: toIso(form.get("ends")), p_duties_en: form.get("dutiesEn"), p_duties_ar: form.get("dutiesAr"), p_private_note: null }), t("academyOperations.success.shift")); }}>
               <p className="font-semibold text-sm">{t("academyOperations.shift.title")}</p><input required aria-label={t("academyOperations.availability.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.availability.staffId")} /><input required aria-label={t("academyOperations.shift.starts")} name="starts" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.shift.ends")} name="ends" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.shift.dutiesEnglish")} name="dutiesEn" className={fieldClass} placeholder={t("academyOperations.shift.dutiesEnglish")} /><input required aria-label={t("academyOperations.shift.dutiesArabic")} dir="rtl" name="dutiesAr" className={fieldClass} placeholder={t("academyOperations.shift.dutiesArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.shift.save")}</PrimaryButton>
            </form>
             <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveLeave({ p_leave_id: null, p_staff_profile_id: form.get("staff"), p_status: form.get("status"), p_starts_at: toIso(form.get("starts")), p_ends_at: toIso(form.get("ends")), p_reason_en: form.get("reasonEn"), p_reason_ar: form.get("reasonAr") }), t("academyOperations.success.leave")); }}>
               <p className="font-semibold text-sm">{t("academyOperations.leave.title")}</p><input required aria-label={t("academyOperations.availability.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.availability.staffId")} /><select aria-label={t("academyOperations.leave.status")} name="status" className={fieldClass}><option value="requested">{t("academyOperations.leave.statuses.requested")}</option><option value="approved">{t("academyOperations.leave.statuses.approved")}</option></select><input required aria-label={t("academyOperations.leave.starts")} name="starts" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.leave.ends")} name="ends" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.leave.reasonEnglish")} name="reasonEn" className={fieldClass} placeholder={t("academyOperations.leave.reasonEnglish")} /><input required aria-label={t("academyOperations.leave.reasonArabic")} dir="rtl" name="reasonAr" className={fieldClass} placeholder={t("academyOperations.leave.reasonArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.leave.save")}</PrimaryButton>
            </form>
             <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveCoachAllocation({ p_allocation_id: null, p_coach_staff_profile_id: form.get("coach"), p_rider_id: form.get("rider"), p_starts_at: toIso(form.get("starts")), p_ends_at: form.get("ends") ? toIso(form.get("ends")) : null, p_status: "active", p_allocation_note_en: form.get("noteEn"), p_allocation_note_ar: form.get("noteAr") }), t("academyOperations.success.allocation")); }}>
               <p className="font-semibold text-sm">{t("academyOperations.allocation.title")}</p><input required aria-label={t("academyOperations.allocation.coachId")} name="coach" className={fieldClass} placeholder={t("academyOperations.allocation.coachId")} /><input required aria-label={t("academyOperations.allocation.riderId")} name="rider" className={fieldClass} placeholder={t("academyOperations.allocation.riderId")} /><input required aria-label={t("academyOperations.allocation.starts")} name="starts" type="datetime-local" className={fieldClass} /><input aria-label={t("academyOperations.allocation.ends")} name="ends" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.allocation.noteEnglish")} name="noteEn" className={fieldClass} placeholder={t("academyOperations.allocation.noteEnglish")} /><input required aria-label={t("academyOperations.allocation.noteArabic")} dir="rtl" name="noteAr" className={fieldClass} placeholder={t("academyOperations.allocation.noteArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.allocation.save")}</PrimaryButton>
            </form>
          </div>
        </details>
      </Panel>

      <Panel title={t("academyOperations.panels.resources")} icon={Building2}>
        <form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => {
          event.preventDefault(); const form = new FormData(event.currentTarget);
          void submit(() => actions.saveResource({
            p_resource_id: null, p_resource_type: form.get("resourceType"), p_name_en: form.get("nameEn"), p_name_ar: form.get("nameAr"),
            p_capacity: Number(form.get("capacity")), p_active: true, p_details_en: null, p_details_ar: null,
          }), t("academyOperations.success.resource"));
        }}>
          <label className={labelClass}>{t("academyOperations.resources.type")}<select aria-label={t("academyOperations.resources.type")} name="resourceType" className={fieldClass}><option value="arena">{t("academyOperations.resources.types.arena")}</option><option value="equipment">{t("academyOperations.resources.types.equipment")}</option></select></label>
          <label className={labelClass}>{t("academyOperations.resources.capacity")}<input required min="1" max="500" defaultValue="1" name="capacity" type="number" className={fieldClass} /></label>
          <label className={labelClass}>{t("academyOperations.resources.englishName")}<input required name="nameEn" className={fieldClass} /></label>
          <label className={labelClass}>{t("academyOperations.resources.arabicName")}<input required dir="rtl" name="nameAr" className={fieldClass} /></label>
          <PrimaryButton type="submit" disabled={actions.saving} className="md:col-span-2">{t("academyOperations.resources.add")}</PrimaryButton>
        </form>
        <div className="mt-5 space-y-2">{data.resources.length ? data.resources.slice(0, 6).map((resource) => <div key={resource.id} className="flex items-center justify-between rounded-lg border border-cream-200 px-3 py-2 text-sm"><span>{resource.name_en} <span dir="rtl">· {resource.name_ar}</span></span><span className="text-text-secondary">{t(`academyOperations.resources.types.${resource.resource_type}`)} · {resource.capacity}</span></div>) : <p className="rounded-lg border border-dashed border-cream-300 bg-cream-50 px-3 py-4 text-sm text-text-secondary">{t("academyOperations.resources.none")}</p>}</div>
        <details className="mt-5 rounded-xl border border-cream-200 p-4"><summary className="cursor-pointer font-semibold text-espresso">{t("academyOperations.resources.bookingDetails")}</summary><form className="mt-4 grid gap-2 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveBooking({ p_booking_id: null, p_resource_id: form.get("resource"), p_staff_profile_id: form.get("staff") || null, p_lesson_id: form.get("lesson") || null, p_status: "confirmed", p_starts_at: toIso(form.get("starts")), p_ends_at: toIso(form.get("ends")), p_purpose_en: form.get("purposeEn"), p_purpose_ar: form.get("purposeAr") }), t("academyOperations.success.booking")); }}>
          <input required aria-label={t("academyOperations.booking.resourceId")} name="resource" className={fieldClass} placeholder={t("academyOperations.booking.resourceId")} /><input aria-label={t("academyOperations.booking.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.booking.staffId")} /><input aria-label={t("academyOperations.booking.lessonId")} name="lesson" className={fieldClass} placeholder={t("academyOperations.booking.lessonId")} /><input required aria-label={t("academyOperations.booking.starts")} name="starts" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.booking.ends")} name="ends" type="datetime-local" className={fieldClass} /><input required aria-label={t("academyOperations.booking.purposeEnglish")} name="purposeEn" className={fieldClass} placeholder={t("academyOperations.booking.purposeEnglish")} /><input required aria-label={t("academyOperations.booking.purposeArabic")} dir="rtl" name="purposeAr" className={fieldClass} placeholder={t("academyOperations.booking.purposeArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.booking.save")}</PrimaryButton>
        </form></details>
      </Panel>

      <Panel title={t("academyOperations.panels.capacity")} icon={CalendarDays}>
        <p className="mb-3 text-sm text-text-secondary">{t("academyOperations.capacity.notice")}</p>
        <div className="space-y-2">{data.lessonCapacity.length ? data.lessonCapacity.slice(0, 6).map((control) => <div key={control.id} className="flex items-center justify-between rounded-lg border border-cream-200 px-3 py-2 text-sm"><span>{t("academyOperations.capacity.lesson", { id: control.lesson_id.slice(0, 8) })}</span><span>{t("academyOperations.capacity.summary", { confirmed: control.confirmed_count, capacity: control.capacity, waitlist: control.waitlist_count })}</span></div>) : <p className="rounded-lg border border-dashed border-cream-300 bg-cream-50 px-3 py-4 text-sm text-text-secondary">{t("academyOperations.capacity.none")}</p>}</div>
        <div className="mt-5 border-t border-cream-200 pt-4 text-sm text-text-secondary">{t("academyOperations.capacity.bookings", { count: data.bookings.length })}</div>
        <details className="mt-5 rounded-xl border border-cream-200 p-4"><summary className="cursor-pointer font-semibold text-espresso">{t("academyOperations.capacity.configure")}</summary><form className="mt-4 grid gap-2 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveCapacity({ p_lesson_id: form.get("lesson"), p_capacity: Number(form.get("capacity")), p_confirmed_count: Number(form.get("confirmed")), p_waitlist_count: Number(form.get("waitlist")), p_status: form.get("status"), p_note_en: form.get("noteEn"), p_note_ar: form.get("noteAr") }), t("academyOperations.success.capacity")); }}>
          <input required aria-label={t("academyOperations.booking.lessonId")} name="lesson" className={fieldClass} placeholder={t("academyOperations.booking.lessonId")} /><select aria-label={t("academyOperations.capacity.status")} name="status" className={fieldClass}><option value="open">{t("academyOperations.capacity.statuses.open")}</option><option value="waitlist">{t("academyOperations.capacity.statuses.waitlist")}</option><option value="closed">{t("academyOperations.capacity.statuses.closed")}</option></select><input required aria-label={t("academyOperations.capacity.capacity")} min="1" name="capacity" type="number" defaultValue="1" className={fieldClass} /><input required aria-label={t("academyOperations.capacity.confirmed")} min="0" name="confirmed" type="number" defaultValue="0" className={fieldClass} /><input required aria-label={t("academyOperations.capacity.waitlist")} min="0" name="waitlist" type="number" defaultValue="0" className={fieldClass} /><input aria-label={t("academyOperations.capacity.noteEnglish")} name="noteEn" className={fieldClass} placeholder={t("academyOperations.capacity.noteEnglish")} /><input aria-label={t("academyOperations.capacity.noteArabic")} dir="rtl" name="noteAr" className={fieldClass} placeholder={t("academyOperations.capacity.noteArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.capacity.save")}</PrimaryButton>
        </form></details>
      </Panel>

      <Panel title={t("academyOperations.panels.inspections")} icon={HardHat}>
        <div className="grid grid-cols-3 gap-3 text-center text-sm"><div><p className="font-serif text-2xl text-espresso">{data.inspections.length}</p><p className="text-text-secondary">{t("academyOperations.inspections.counts.inspections")}</p></div><div><p className="font-serif text-2xl text-espresso">{data.workOrders.filter((order) => order.status !== "completed").length}</p><p className="text-text-secondary">{t("academyOperations.inspections.counts.openWork")}</p></div><div><p className="font-serif text-2xl text-espresso">{data.alerts.filter((alert) => alert.status === "open").length}</p><p className="text-text-secondary">{t("academyOperations.inspections.counts.alerts")}</p></div></div>
        <div className="mt-5 space-y-2">{data.alerts.length ? data.alerts.slice(0, 4).map((alert) => <div key={alert.id} className="rounded-lg border border-cream-200 px-3 py-2 text-sm"><div className="flex justify-between gap-3"><span>{alert.title_en}</span><StatusBadge status={alert.severity} label={t(`academyOperations.alert.severities.${alert.severity}`)} /></div><p className="mt-1 text-text-secondary" dir="rtl">{alert.title_ar}</p></div>) : <p className="rounded-lg border border-dashed border-cream-300 bg-cream-50 px-3 py-4 text-sm text-text-secondary">{t("academyOperations.inspections.none")}</p>}</div>
        <details className="mt-5 rounded-xl border border-cream-200 p-4"><summary className="cursor-pointer font-semibold text-espresso">{t("academyOperations.inspections.actions")}</summary><div className="mt-4 grid gap-5 lg:grid-cols-3">
          <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveInspection({ p_inspection_id: null, p_resource_id: form.get("resource") || null, p_inspection_type: form.get("type"), p_inspected_at: new Date().toISOString(), p_result: form.get("result"), p_findings_en: form.get("findingsEn"), p_findings_ar: form.get("findingsAr"), p_corrective_action_en: form.get("actionEn"), p_corrective_action_ar: form.get("actionAr"), p_next_due_at: null, p_private_note: null }), t("academyOperations.success.inspection")); }}><p className="font-semibold text-sm">{t("academyOperations.inspection.title")}</p><input aria-label={t("academyOperations.inspection.resourceId")} name="resource" className={fieldClass} placeholder={t("academyOperations.inspection.resourceId")} /><select aria-label={t("academyOperations.inspection.type")} name="type" className={fieldClass}><option value="arena">{t("academyOperations.inspection.types.arena")}</option><option value="equipment">{t("academyOperations.inspection.types.equipment")}</option><option value="facility">{t("academyOperations.inspection.types.facility")}</option></select><select aria-label={t("academyOperations.inspection.result")} name="result" className={fieldClass}><option value="safe">{t("academyOperations.inspection.results.safe")}</option><option value="attention">{t("academyOperations.inspection.results.attention")}</option><option value="unsafe">{t("academyOperations.inspection.results.unsafe")}</option></select><input required aria-label={t("academyOperations.inspection.findingsEnglish")} name="findingsEn" className={fieldClass} placeholder={t("academyOperations.inspection.findingsEnglish")} /><input required aria-label={t("academyOperations.inspection.findingsArabic")} dir="rtl" name="findingsAr" className={fieldClass} placeholder={t("academyOperations.inspection.findingsArabic")} /><input required aria-label={t("academyOperations.inspection.actionEnglish")} name="actionEn" className={fieldClass} placeholder={t("academyOperations.inspection.actionEnglish")} /><input required aria-label={t("academyOperations.inspection.actionArabic")} dir="rtl" name="actionAr" className={fieldClass} placeholder={t("academyOperations.inspection.actionArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.inspection.save")}</PrimaryButton></form>
          <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveWorkOrder({ p_work_order_id: null, p_inspection_id: form.get("inspection") || null, p_resource_id: form.get("resource") || null, p_priority: form.get("priority"), p_status: "open", p_title_en: form.get("titleEn"), p_title_ar: form.get("titleAr"), p_details_en: form.get("detailsEn"), p_details_ar: form.get("detailsAr"), p_due_at: form.get("due") ? toIso(form.get("due")) : null, p_private_note: null }), t("academyOperations.success.workOrder")); }}><p className="font-semibold text-sm">{t("academyOperations.workOrder.title")}</p><input aria-label={t("academyOperations.workOrder.inspectionId")} name="inspection" className={fieldClass} placeholder={t("academyOperations.workOrder.inspectionId")} /><input aria-label={t("academyOperations.workOrder.resourceId")} name="resource" className={fieldClass} placeholder={t("academyOperations.workOrder.resourceId")} /><select aria-label={t("academyOperations.workOrder.priority")} name="priority" className={fieldClass}><option value="normal">{t("academyOperations.workOrder.priorities.normal")}</option><option value="high">{t("academyOperations.workOrder.priorities.high")}</option><option value="urgent">{t("academyOperations.workOrder.priorities.urgent")}</option></select><input required aria-label={t("academyOperations.workOrder.titleEnglish")} name="titleEn" className={fieldClass} placeholder={t("academyOperations.workOrder.titleEnglish")} /><input required aria-label={t("academyOperations.workOrder.titleArabic")} dir="rtl" name="titleAr" className={fieldClass} placeholder={t("academyOperations.workOrder.titleArabic")} /><input required aria-label={t("academyOperations.workOrder.detailsEnglish")} name="detailsEn" className={fieldClass} placeholder={t("academyOperations.workOrder.detailsEnglish")} /><input required aria-label={t("academyOperations.workOrder.detailsArabic")} name="detailsAr" className={fieldClass} placeholder={t("academyOperations.workOrder.detailsArabic")} /><input aria-label={t("academyOperations.workOrder.due")} name="due" type="datetime-local" className={fieldClass} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.workOrder.save")}</PrimaryButton></form>
          <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.createAlert({ p_alert_type: form.get("type"), p_severity: form.get("severity"), p_title_en: form.get("titleEn"), p_title_ar: form.get("titleAr"), p_body_en: form.get("bodyEn"), p_body_ar: form.get("bodyAr"), p_source_type: null, p_source_id: null, p_due_at: null }), t("academyOperations.success.alert")); }}><p className="font-semibold text-sm">{t("academyOperations.alert.title")}</p><select aria-label={t("academyOperations.alert.type")} name="type" className={fieldClass}><option value="staffing">{t("academyOperations.alert.types.staffing")}</option><option value="booking">{t("academyOperations.alert.types.booking")}</option><option value="capacity">{t("academyOperations.alert.types.capacity")}</option><option value="inspection">{t("academyOperations.alert.types.inspection")}</option><option value="maintenance">{t("academyOperations.alert.types.maintenance")}</option></select><select aria-label={t("academyOperations.alert.severity")} name="severity" className={fieldClass}><option value="attention">{t("academyOperations.alert.severities.attention")}</option><option value="urgent">{t("academyOperations.alert.severities.urgent")}</option><option value="critical">{t("academyOperations.alert.severities.critical")}</option></select><input required aria-label={t("academyOperations.alert.titleEnglish")} name="titleEn" className={fieldClass} placeholder={t("academyOperations.alert.titleEnglish")} /><input required aria-label={t("academyOperations.alert.titleArabic")} dir="rtl" name="titleAr" className={fieldClass} placeholder={t("academyOperations.alert.titleArabic")} /><input required aria-label={t("academyOperations.alert.bodyEnglish")} name="bodyEn" className={fieldClass} placeholder={t("academyOperations.alert.bodyEnglish")} /><input required aria-label={t("academyOperations.alert.bodyArabic")} dir="rtl" name="bodyAr" className={fieldClass} placeholder={t("academyOperations.alert.bodyArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.alert.save")}</PrimaryButton></form>
        </div></details>
      </Panel>
    </div>

    <Panel title={t("academyOperations.panels.compensation")} icon={WalletCards}>
      {access.data.canViewCompensation ? <div className="grid gap-5 lg:grid-cols-2">
        <div><p className="text-sm text-text-secondary">{t("academyOperations.compensation.reviewNotice")}</p><div className="mt-4 space-y-2">{data.payroll.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 rounded-lg border border-cream-200 px-3 py-2 text-sm"><span>{entry.period_start} – {entry.period_end}</span><span className="flex items-center gap-2">{entry.currency} {entry.calculated_amount} · <StatusBadge status={entry.approval_status} label={t(`academyOperations.compensation.statuses.${entry.approval_status}`)} />{canApproveCompensation && entry.approval_status === "submitted" ? <PrimaryButton type="button" disabled={actions.saving} onClick={() => { void submit(() => actions.approvePayroll(entry.id), t("academyOperations.success.payrollApproved")); }}>{t("academyOperations.compensation.approvePayroll")}</PrimaryButton> : null}</span></div>)}</div>
          <div className="mt-4 border-t border-cream-200 pt-4"><p className="mb-2 text-sm font-semibold text-espresso">{t("academyOperations.compensation.commissionReview")}</p>{data.commissions.map((entry) => <div key={entry.id} className="mb-2 flex items-center justify-between gap-3 rounded-lg border border-cream-200 px-3 py-2 text-sm"><span>{entry.period_start} – {entry.period_end}</span><span className="flex items-center gap-2">{entry.currency} {entry.calculated_amount} · <StatusBadge status={entry.approval_status} label={t(`academyOperations.compensation.statuses.${entry.approval_status}`)} />{canApproveCompensation && entry.approval_status === "submitted" ? <PrimaryButton type="button" disabled={actions.saving} onClick={() => { void submit(() => actions.approveCommission(entry.id), t("academyOperations.success.commissionApproved")); }}>{t("academyOperations.compensation.approveCommission")}</PrimaryButton> : null}</span></div>)}</div></div>
        <div className="rounded-xl border border-primary-200 bg-primary-50 p-4"><p className="font-semibold text-primary-900">{t("academyOperations.compensation.safeguards")}</p><ul className="mt-2 list-disc space-y-1 ps-5 text-sm text-primary-900"><li>{t("academyOperations.compensation.visibleTo")}</li><li>{t("academyOperations.compensation.approveOnly")}</li><li>{t("academyOperations.compensation.audited")}</li></ul><p className="mt-3 text-xs text-primary-800">{t("academyOperations.compensation.inReview", { count: data.commissions.length })} {t("academyOperations.compensation.lastBooking", { date: data.bookings[0] ? localTime(data.bookings[0].updated_at, locale) : "—" })}</p></div>
        <details className="lg:col-span-2 rounded-xl border border-cream-200 p-4"><summary className="cursor-pointer font-semibold text-espresso">{t("academyOperations.compensation.create")}</summary><div className="mt-4 grid gap-5 lg:grid-cols-2">
          <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.savePayroll({ p_calculation_id: null, p_staff_profile_id: form.get("staff"), p_period_start: form.get("start"), p_period_end: form.get("end"), p_currency: form.get("currency"), p_gross_amount: Number(form.get("gross")), p_adjustment_amount: Number(form.get("adjustment")), p_calculated_amount: Number(form.get("amount")), p_approval_status: form.get("status"), p_calculation_note_en: form.get("noteEn"), p_calculation_note_ar: form.get("noteAr"), p_private_note: null }), t("academyOperations.success.payroll")); }}><p className="font-semibold text-sm">{t("academyOperations.compensation.payroll")}</p><input required aria-label={t("academyOperations.compensation.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.compensation.staffId")} /><input required aria-label={t("academyOperations.compensation.periodStart")} name="start" type="date" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.periodEnd")} name="end" type="date" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.currency")} name="currency" defaultValue="USD" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.gross")} name="gross" type="number" step="0.01" defaultValue="0" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.adjustment")} name="adjustment" type="number" step="0.01" defaultValue="0" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.calculated")} name="amount" type="number" step="0.01" defaultValue="0" className={fieldClass} /><select aria-label={t("academyOperations.compensation.status")} name="status" className={fieldClass}><option value="draft">{t("academyOperations.compensation.statuses.draft")}</option><option value="submitted">{t("academyOperations.compensation.statuses.submitted")}</option></select><input required aria-label={t("academyOperations.compensation.noteEnglish")} name="noteEn" className={fieldClass} placeholder={t("academyOperations.compensation.noteEnglish")} /><input required aria-label={t("academyOperations.compensation.noteArabic")} dir="rtl" name="noteAr" className={fieldClass} placeholder={t("academyOperations.compensation.noteArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.compensation.savePayroll")}</PrimaryButton></form>
          <form className="grid gap-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(() => actions.saveCommission({ p_calculation_id: null, p_staff_profile_id: form.get("staff"), p_period_start: form.get("start"), p_period_end: form.get("end"), p_currency: form.get("currency"), p_basis_amount: Number(form.get("basis")), p_commission_rate: Number(form.get("rate")), p_calculated_amount: Number(form.get("amount")), p_approval_status: form.get("status"), p_calculation_note_en: form.get("noteEn"), p_calculation_note_ar: form.get("noteAr"), p_private_note: null }), t("academyOperations.success.commission")); }}><p className="font-semibold text-sm">{t("academyOperations.compensation.commission")}</p><input required aria-label={t("academyOperations.compensation.staffId")} name="staff" className={fieldClass} placeholder={t("academyOperations.compensation.staffId")} /><input required aria-label={t("academyOperations.compensation.periodStart")} name="start" type="date" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.periodEnd")} name="end" type="date" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.currency")} name="currency" defaultValue="USD" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.basis")} name="basis" type="number" step="0.01" defaultValue="0" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.rate")} name="rate" type="number" step="0.01" min="0" max="100" defaultValue="0" className={fieldClass} /><input required aria-label={t("academyOperations.compensation.calculated")} name="amount" type="number" step="0.01" defaultValue="0" className={fieldClass} /><select aria-label={t("academyOperations.compensation.status")} name="status" className={fieldClass}><option value="draft">{t("academyOperations.compensation.statuses.draft")}</option><option value="submitted">{t("academyOperations.compensation.statuses.submitted")}</option></select><input required aria-label={t("academyOperations.compensation.noteEnglish")} name="noteEn" className={fieldClass} placeholder={t("academyOperations.compensation.noteEnglish")} /><input required aria-label={t("academyOperations.compensation.noteArabic")} dir="rtl" name="noteAr" className={fieldClass} placeholder={t("academyOperations.compensation.noteArabic")} /><PrimaryButton type="submit" disabled={actions.saving}>{t("academyOperations.compensation.saveCommission")}</PrimaryButton></form>
        </div></details>
      </div> : <p className="text-sm text-text-secondary">{t("academyOperations.compensation.restricted")}</p>}
    </Panel>
  </div>;
}