begin;

create table public.compliance_obligations(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,obligation_code text not null,jurisdiction text not null,regulator text not null,source_title text not null,source_reference text,category text not null,title text not null,description text not null,applicability text not null,frequency text not null,evidence_required text not null,owner_user_id uuid not null references auth.users(id),status text not null default 'active',effective_on date not null,next_due_on date,last_filed_on date,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),
 constraint compliance_obligation_code_length check(char_length(obligation_code)between 2 and 30),constraint compliance_obligation_jurisdiction_length check(char_length(jurisdiction)between 2 and 120),constraint compliance_obligation_regulator_length check(char_length(regulator)between 2 and 180),constraint compliance_obligation_source_length check(char_length(source_title)between 3 and 300),constraint compliance_obligation_category check(category in('tax','labor','privacy','safety','corporate','financial','industry','environmental')),constraint compliance_obligation_title_length check(char_length(title)between 5 and 180),constraint compliance_obligation_description_length check(char_length(description)between 10 and 3000),constraint compliance_obligation_applicability_length check(char_length(applicability)between 10 and 2000),constraint compliance_obligation_frequency check(frequency in('event_driven','monthly','quarterly','semiannual','annual')),constraint compliance_obligation_evidence_length check(char_length(evidence_required)between 5 and 2000),constraint compliance_obligation_status check(status in('draft','active','retired')),constraint compliance_obligation_dates check(next_due_on is null or next_due_on>=effective_on),unique(academy_id,obligation_code)
);

create table public.compliance_obligation_mappings(
 id uuid primary key default gen_random_uuid(),obligation_id uuid not null references public.compliance_obligations(id) on delete restrict,control_id uuid references public.audit_control_definitions(id) on delete restrict,risk_id uuid references public.enterprise_risks(id) on delete restrict,mapping_type text not null,notes text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),
 constraint compliance_mapping_exactly_one check((control_id is not null)::integer+(risk_id is not null)::integer=1),constraint compliance_mapping_type check((control_id is not null and mapping_type='control')or(risk_id is not null and mapping_type='risk')),constraint compliance_mapping_notes_length check(char_length(notes)between 5 and 2000),unique(obligation_id,control_id),unique(obligation_id,risk_id)
);

create table public.compliance_filings(
 id uuid primary key default gen_random_uuid(),obligation_id uuid not null references public.compliance_obligations(id) on delete restrict,period_starts_on date not null,period_ends_on date not null,due_on date not null,status text not null default 'upcoming',assigned_to uuid not null references auth.users(id),evidence_references jsonb not null default '[]'::jsonb,submission_reference text,attestation_text text,submitted_by uuid references auth.users(id),submitted_at timestamptz,attested_by uuid references auth.users(id),attested_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),
 constraint compliance_filing_period check(period_ends_on>=period_starts_on and due_on>=period_ends_on),constraint compliance_filing_status check(status in('upcoming','in_progress','submitted','waived')),constraint compliance_filing_evidence_array check(jsonb_typeof(evidence_references)='array'),constraint compliance_filing_completion check((status in('upcoming','in_progress')and submitted_by is null and submitted_at is null and attested_by is null and attested_at is null)or(status='submitted'and submitted_by is not null and submitted_at is not null and attested_by is not null and attested_at is not null and char_length(attestation_text)between 20 and 3000 and jsonb_array_length(evidence_references)>0 and char_length(submission_reference)between 2 and 300)or(status='waived'and attested_by is not null and attested_at is not null and char_length(attestation_text)between 20 and 3000)),unique(obligation_id,period_starts_on,period_ends_on)
);

create table public.compliance_breaches(
 id uuid primary key default gen_random_uuid(),obligation_id uuid not null references public.compliance_obligations(id) on delete restrict,filing_id uuid references public.compliance_filings(id) on delete restrict,severity text not null,title text not null,details text not null,root_cause text,remediation_plan text not null,owner_user_id uuid not null references auth.users(id),target_date date not null,status text not null default 'open',resolution_evidence text,closed_by uuid references auth.users(id),closed_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),
 constraint compliance_breach_severity check(severity in('low','medium','high','critical')),constraint compliance_breach_title_length check(char_length(title)between 5 and 180),constraint compliance_breach_details_length check(char_length(details)between 10 and 3000),constraint compliance_breach_plan_length check(char_length(remediation_plan)between 10 and 3000),constraint compliance_breach_status check(status in('open','remediating','ready_for_review','closed')),constraint compliance_breach_close_state check((status<>'closed'and closed_by is null and closed_at is null)or(status='closed'and closed_by is not null and closed_at is not null and char_length(resolution_evidence)between 10 and 4000))
);

create index compliance_obligations_academy_status_idx on public.compliance_obligations(academy_id,status,next_due_on);create index compliance_obligations_owner_idx on public.compliance_obligations(owner_user_id,status);create index compliance_obligations_created_by_idx on public.compliance_obligations(created_by);create index compliance_obligations_updated_by_idx on public.compliance_obligations(updated_by);
create index compliance_mappings_control_idx on public.compliance_obligation_mappings(control_id)where control_id is not null;create index compliance_mappings_risk_idx on public.compliance_obligation_mappings(risk_id)where risk_id is not null;create index compliance_mappings_created_by_idx on public.compliance_obligation_mappings(created_by);
create index compliance_filings_obligation_due_idx on public.compliance_filings(obligation_id,due_on desc);create index compliance_filings_assigned_idx on public.compliance_filings(assigned_to,status);create index compliance_filings_submitted_by_idx on public.compliance_filings(submitted_by)where submitted_by is not null;create index compliance_filings_attested_by_idx on public.compliance_filings(attested_by)where attested_by is not null;create index compliance_filings_created_by_idx on public.compliance_filings(created_by);create index compliance_filings_updated_by_idx on public.compliance_filings(updated_by);
create index compliance_breaches_obligation_status_idx on public.compliance_breaches(obligation_id,status,target_date);create index compliance_breaches_filing_idx on public.compliance_breaches(filing_id)where filing_id is not null;create index compliance_breaches_owner_idx on public.compliance_breaches(owner_user_id,status);create index compliance_breaches_closed_by_idx on public.compliance_breaches(closed_by)where closed_by is not null;create index compliance_breaches_created_by_idx on public.compliance_breaches(created_by);create index compliance_breaches_updated_by_idx on public.compliance_breaches(updated_by);

alter table public.compliance_obligations enable row level security;alter table public.compliance_obligation_mappings enable row level security;alter table public.compliance_filings enable row level security;alter table public.compliance_breaches enable row level security;
revoke all on public.compliance_obligations,public.compliance_obligation_mappings,public.compliance_filings,public.compliance_breaches from public,anon,authenticated;
grant select,insert,update on public.compliance_obligations,public.compliance_filings,public.compliance_breaches to authenticated;grant select,insert on public.compliance_obligation_mappings to authenticated;grant select,insert,update,delete on public.compliance_obligations,public.compliance_obligation_mappings,public.compliance_filings,public.compliance_breaches to service_role;
create policy compliance_obligations_read_admin on public.compliance_obligations for select to authenticated using((select private.is_platform_administrator()));create policy compliance_obligations_insert_admin on public.compliance_obligations for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid())and updated_by=(select auth.uid()));create policy compliance_obligations_update_admin on public.compliance_obligations for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));
create policy compliance_mappings_read_admin on public.compliance_obligation_mappings for select to authenticated using((select private.is_platform_administrator()));create policy compliance_mappings_insert_admin on public.compliance_obligation_mappings for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid()));
create policy compliance_filings_read_admin on public.compliance_filings for select to authenticated using((select private.is_platform_administrator()));create policy compliance_filings_insert_admin on public.compliance_filings for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid())and updated_by=(select auth.uid()));create policy compliance_filings_update_admin on public.compliance_filings for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));
create policy compliance_breaches_read_admin on public.compliance_breaches for select to authenticated using((select private.is_platform_administrator()));create policy compliance_breaches_insert_admin on public.compliance_breaches for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid())and updated_by=(select auth.uid()));create policy compliance_breaches_update_admin on public.compliance_breaches for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));

create function private.protect_terminal_compliance_filing()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status in('submitted','waived')then raise exception 'terminal compliance filing is immutable' using errcode='23514';end if;new.updated_at:=now();return new;end;$$;create trigger protect_terminal_compliance_filing before update or delete on public.compliance_filings for each row execute function private.protect_terminal_compliance_filing();
create function private.protect_closed_compliance_breach()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status='closed'then raise exception 'closed compliance breach is immutable' using errcode='23514';end if;new.updated_at:=now();return new;end;$$;create trigger protect_closed_compliance_breach before update or delete on public.compliance_breaches for each row execute function private.protect_closed_compliance_breach();

create function public.create_compliance_obligation(target_academy_id uuid,target_obligation_code text,target_jurisdiction text,target_regulator text,target_source_title text,target_source_reference text,target_category text,target_title text,target_description text,target_applicability text,target_frequency text,target_evidence_required text,target_owner_user_id uuid,target_effective_on date,target_next_due_on date)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;if not exists(select 1 from public.academies where id=target_academy_id and archived_at is null)or not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')then raise exception 'active academy and owner required' using errcode='23514';end if;insert into public.compliance_obligations(academy_id,obligation_code,jurisdiction,regulator,source_title,source_reference,category,title,description,applicability,frequency,evidence_required,owner_user_id,effective_on,next_due_on,created_by,updated_by)values(target_academy_id,upper(btrim(target_obligation_code)),btrim(target_jurisdiction),btrim(target_regulator),btrim(target_source_title),nullif(btrim(coalesce(target_source_reference,'')),''),target_category,btrim(target_title),btrim(target_description),btrim(target_applicability),target_frequency,btrim(target_evidence_required),target_owner_user_id,target_effective_on,target_next_due_on,actor,actor)returning id into created_id;perform public.write_audit_event(target_academy_id,'compliance.obligation_created','compliance_obligation',created_id,jsonb_build_object('code',upper(btrim(target_obligation_code)),'regulator',target_regulator));return created_id;end;$$;
create function public.update_compliance_obligation(target_obligation_id uuid,target_status text,target_owner_user_id uuid,target_next_due_on date,target_evidence_required text)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_obligations%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_obligations where id=target_obligation_id for update;if scoped.id is null or not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')then raise exception 'obligation and active owner required' using errcode='23514';end if;if target_status='retired'and exists(select 1 from public.compliance_filings where obligation_id=scoped.id and status in('upcoming','in_progress'))then raise exception 'open filings must be completed before retirement' using errcode='23514';end if;update public.compliance_obligations set status=target_status,owner_user_id=target_owner_user_id,next_due_on=target_next_due_on,evidence_required=btrim(target_evidence_required),updated_by=actor where id=scoped.id;perform public.write_audit_event(scoped.academy_id,'compliance.obligation_updated','compliance_obligation',scoped.id,jsonb_build_object('status',target_status,'next_due_on',target_next_due_on));return true;end;$$;
create function public.map_compliance_obligation(target_obligation_id uuid,target_control_id uuid,target_risk_id uuid,target_notes text)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_obligations%rowtype;created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_obligations where id=target_obligation_id and status='active';if scoped.id is null or((target_control_id is null)=(target_risk_id is null))or(target_control_id is not null and not exists(select 1 from public.audit_control_definitions where id=target_control_id and academy_id=scoped.academy_id and status='active'))or(target_risk_id is not null and not exists(select 1 from public.enterprise_risks where id=target_risk_id and academy_id=scoped.academy_id and status<>'closed'))then raise exception 'active obligation and one same-academy mapping required' using errcode='23514';end if;insert into public.compliance_obligation_mappings(obligation_id,control_id,risk_id,mapping_type,notes,created_by)values(scoped.id,target_control_id,target_risk_id,case when target_control_id is not null then'control'else'risk'end,btrim(target_notes),actor)returning id into created_id;perform public.write_audit_event(scoped.academy_id,'compliance.mapping_created','compliance_obligation',scoped.id,jsonb_build_object('control_id',target_control_id,'risk_id',target_risk_id));return created_id;end;$$;
create function public.schedule_compliance_filing(target_obligation_id uuid,target_period_starts_on date,target_period_ends_on date,target_due_on date,target_assigned_to uuid)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_obligations%rowtype;created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_obligations where id=target_obligation_id and status='active';if scoped.id is null or not exists(select 1 from public.platform_access where user_id=target_assigned_to and status='active')then raise exception 'active obligation and assignee required' using errcode='23514';end if;insert into public.compliance_filings(obligation_id,period_starts_on,period_ends_on,due_on,assigned_to,created_by,updated_by)values(scoped.id,target_period_starts_on,target_period_ends_on,target_due_on,target_assigned_to,actor,actor)returning id into created_id;update public.compliance_obligations set next_due_on=target_due_on,updated_by=actor where id=scoped.id;perform public.write_audit_event(scoped.academy_id,'compliance.filing_scheduled','compliance_filing',created_id,jsonb_build_object('due_on',target_due_on));return created_id;end;$$;
create function public.complete_compliance_filing(target_filing_id uuid,target_status text,target_submission_reference text,target_attestation_text text,target_evidence_references jsonb)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_filings%rowtype;academy uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;if target_status not in('submitted','waived')or char_length(btrim(coalesce(target_attestation_text,'')))not between 20 and 3000 or(target_status='submitted'and(char_length(btrim(coalesce(target_submission_reference,'')))not between 2 and 300 or jsonb_typeof(target_evidence_references)<>'array'or jsonb_array_length(target_evidence_references)=0))then raise exception 'evidence, submission reference, and attestation required' using errcode='23514';end if;select*into scoped from public.compliance_filings where id=target_filing_id and status in('upcoming','in_progress')for update;if scoped.id is null then raise exception 'open compliance filing required' using errcode='23514';end if;select o.academy_id into academy from public.compliance_obligations o where o.id=scoped.obligation_id;update public.compliance_filings set status=target_status,evidence_references=coalesce(target_evidence_references,'[]'::jsonb),submission_reference=case when target_status='submitted'then btrim(target_submission_reference)end,attestation_text=btrim(target_attestation_text),submitted_by=case when target_status='submitted'then actor end,submitted_at=case when target_status='submitted'then now()end,attested_by=actor,attested_at=now(),updated_by=actor where id=scoped.id;if target_status='submitted'then update public.compliance_obligations set last_filed_on=current_date,updated_by=actor where id=scoped.obligation_id;end if;perform public.write_audit_event(academy,'compliance.filing_'||target_status,'compliance_filing',scoped.id,jsonb_build_object('evidence_count',coalesce(jsonb_array_length(target_evidence_references),0)));return true;end;$$;
create function public.open_compliance_breach(target_obligation_id uuid,target_filing_id uuid,target_severity text,target_title text,target_details text,target_remediation_plan text,target_owner_user_id uuid,target_date date)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_obligations%rowtype;created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_obligations where id=target_obligation_id and status='active';if scoped.id is null or not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')or(target_filing_id is not null and not exists(select 1 from public.compliance_filings where id=target_filing_id and obligation_id=scoped.id))then raise exception 'active obligation, owner, and scoped filing required' using errcode='23514';end if;insert into public.compliance_breaches(obligation_id,filing_id,severity,title,details,remediation_plan,owner_user_id,target_date,created_by,updated_by)values(scoped.id,target_filing_id,target_severity,btrim(target_title),btrim(target_details),btrim(target_remediation_plan),target_owner_user_id,target_date,actor,actor)returning id into created_id;perform public.write_audit_event(scoped.academy_id,'compliance.breach_opened','compliance_breach',created_id,jsonb_build_object('severity',target_severity));return created_id;end;$$;
create function public.update_compliance_breach(target_breach_id uuid,target_status text,target_root_cause text,target_remediation_plan text,target_owner_user_id uuid,target_date date)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_breaches%rowtype;academy uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_breaches where id=target_breach_id and status<>'closed'for update;if scoped.id is null or target_status not in('open','remediating','ready_for_review')or not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')then raise exception 'open breach, valid status, and active owner required' using errcode='23514';end if;select o.academy_id into academy from public.compliance_obligations o where o.id=scoped.obligation_id;update public.compliance_breaches set status=target_status,root_cause=nullif(btrim(coalesce(target_root_cause,'')),''),remediation_plan=btrim(target_remediation_plan),owner_user_id=target_owner_user_id,target_date=target_date,updated_by=actor where id=scoped.id;perform public.write_audit_event(academy,'compliance.breach_'||target_status,'compliance_breach',scoped.id,'{}'::jsonb);return true;end;$$;
create function public.close_compliance_breach(target_breach_id uuid,target_resolution_evidence text)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.compliance_breaches%rowtype;academy uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.compliance_breaches where id=target_breach_id and status='ready_for_review'for update;if scoped.id is null or char_length(btrim(target_resolution_evidence))not between 10 and 4000 then raise exception 'review-ready breach and resolution evidence required' using errcode='23514';end if;select o.academy_id into academy from public.compliance_obligations o where o.id=scoped.obligation_id;update public.compliance_breaches set status='closed',resolution_evidence=btrim(target_resolution_evidence),closed_by=actor,closed_at=now(),updated_by=actor where id=scoped.id;perform public.write_audit_event(academy,'compliance.breach_closed','compliance_breach',scoped.id,'{}'::jsonb);return true;end;$$;

revoke all on function private.protect_terminal_compliance_filing(),private.protect_closed_compliance_breach()from public,anon,authenticated;
revoke all on function public.create_compliance_obligation(uuid,text,text,text,text,text,text,text,text,text,text,text,uuid,date,date),public.update_compliance_obligation(uuid,text,uuid,date,text),public.map_compliance_obligation(uuid,uuid,uuid,text),public.schedule_compliance_filing(uuid,date,date,date,uuid),public.complete_compliance_filing(uuid,text,text,text,jsonb),public.open_compliance_breach(uuid,uuid,text,text,text,text,uuid,date),public.update_compliance_breach(uuid,text,text,text,uuid,date),public.close_compliance_breach(uuid,text)from public,anon,authenticated;
grant execute on function public.create_compliance_obligation(uuid,text,text,text,text,text,text,text,text,text,text,text,uuid,date,date),public.update_compliance_obligation(uuid,text,uuid,date,text),public.map_compliance_obligation(uuid,uuid,uuid,text),public.schedule_compliance_filing(uuid,date,date,date,uuid),public.complete_compliance_filing(uuid,text,text,text,jsonb),public.open_compliance_breach(uuid,uuid,text,text,text,text,uuid,date),public.update_compliance_breach(uuid,text,text,text,uuid,date),public.close_compliance_breach(uuid,text)to authenticated;

commit;
