begin;

create type public.fixed_asset_category as enum('horse','vehicle','equipment','facility','technology','other');
create type public.fixed_asset_status as enum('active','fully_depreciated','disposed');

create table public.fixed_assets(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,
 asset_code text not null,name text not null,category public.fixed_asset_category not null,linked_horse_id uuid references public.horses(id) on delete restrict,
 acquired_on date not null,in_service_on date not null,currency text not null check(currency~'^[A-Z]{3}$'),purchase_cost_minor bigint not null,residual_value_minor bigint not null default 0,useful_life_months integer not null,
 asset_account_id uuid not null references public.gl_accounts(id) on delete restrict,accumulated_depreciation_account_id uuid not null references public.gl_accounts(id) on delete restrict,depreciation_expense_account_id uuid not null references public.gl_accounts(id) on delete restrict,
 accumulated_depreciation_minor bigint not null default 0,status public.fixed_asset_status not null default 'active',acquisition_entry_id uuid unique references public.gl_journal_entries(id) on delete restrict,
 disposal_date date,disposal_proceeds_minor bigint,disposal_gain_loss_minor bigint,disposal_entry_id uuid unique references public.gl_journal_entries(id) on delete restrict,disposal_reason text,
 created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint fixed_asset_code_length check(asset_code~'^[A-Za-z0-9][A-Za-z0-9._-]{1,39}$'),constraint fixed_asset_name_length check(char_length(name) between 2 and 160),
 constraint fixed_asset_dates check(in_service_on>=acquired_on),constraint fixed_asset_values check(purchase_cost_minor>0 and residual_value_minor>=0 and residual_value_minor<purchase_cost_minor and useful_life_months between 1 and 600 and accumulated_depreciation_minor between 0 and purchase_cost_minor-residual_value_minor),
 constraint fixed_asset_disposal_state check((status='disposed')=(disposal_date is not null and disposal_proceeds_minor is not null and disposal_gain_loss_minor is not null and disposal_entry_id is not null) and (disposal_reason is null or char_length(disposal_reason) between 2 and 240)),unique(academy_id,asset_code)
);
create table public.fixed_asset_depreciation_runs(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,period_end date not null,currency text not null check(currency~'^[A-Z]{3}$'),total_depreciation_minor bigint not null check(total_depreciation_minor>0),journal_entry_id uuid unique references public.gl_journal_entries(id) on delete restrict,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(academy_id,currency,period_end)
);
create table public.fixed_asset_depreciation_lines(
 id uuid primary key default gen_random_uuid(),run_id uuid not null references public.fixed_asset_depreciation_runs(id) on delete restrict,academy_id uuid not null references public.academies(id) on delete restrict,asset_id uuid not null references public.fixed_assets(id) on delete restrict,opening_accumulated_minor bigint not null check(opening_accumulated_minor>=0),depreciation_minor bigint not null check(depreciation_minor>0),closing_accumulated_minor bigint not null check(closing_accumulated_minor=opening_accumulated_minor+depreciation_minor),created_at timestamptz not null default now(),unique(run_id,asset_id)
);

create index fixed_assets_academy_status_idx on public.fixed_assets(academy_id,status,asset_code);create index fixed_assets_horse_idx on public.fixed_assets(linked_horse_id) where linked_horse_id is not null;create index fixed_assets_asset_account_idx on public.fixed_assets(asset_account_id);create index fixed_assets_accumulated_account_idx on public.fixed_assets(accumulated_depreciation_account_id);create index fixed_assets_expense_account_idx on public.fixed_assets(depreciation_expense_account_id);create index fixed_assets_created_by_idx on public.fixed_assets(created_by);create index fixed_assets_updated_by_idx on public.fixed_assets(updated_by);create index depreciation_runs_academy_period_idx on public.fixed_asset_depreciation_runs(academy_id,period_end desc);create index depreciation_runs_created_by_idx on public.fixed_asset_depreciation_runs(created_by);create index depreciation_lines_academy_asset_idx on public.fixed_asset_depreciation_lines(academy_id,asset_id);create index depreciation_lines_asset_idx on public.fixed_asset_depreciation_lines(asset_id);

alter table public.fixed_assets enable row level security;alter table public.fixed_asset_depreciation_runs enable row level security;alter table public.fixed_asset_depreciation_lines enable row level security;
revoke all on public.fixed_assets,public.fixed_asset_depreciation_runs,public.fixed_asset_depreciation_lines from public,anon,authenticated;
grant select,insert,update on public.fixed_assets to authenticated;grant select,insert,update on public.fixed_asset_depreciation_runs to authenticated;grant select,insert on public.fixed_asset_depreciation_lines to authenticated;grant select,insert,update,delete on public.fixed_assets,public.fixed_asset_depreciation_runs,public.fixed_asset_depreciation_lines to service_role;
grant usage on type public.fixed_asset_category,public.fixed_asset_status to authenticated;
create policy fixed_assets_read_administrators on public.fixed_assets for select to authenticated using((select private.is_platform_administrator()));
create policy fixed_assets_insert_administrators on public.fixed_assets for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()) and updated_by=(select auth.uid()));
create policy fixed_assets_update_administrators on public.fixed_assets for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()) and updated_by=(select auth.uid()));
create policy depreciation_runs_read_administrators on public.fixed_asset_depreciation_runs for select to authenticated using((select private.is_platform_administrator()));
create policy depreciation_runs_insert_administrators on public.fixed_asset_depreciation_runs for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));
create policy depreciation_runs_update_administrators on public.fixed_asset_depreciation_runs for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy depreciation_lines_read_administrators on public.fixed_asset_depreciation_lines for select to authenticated using((select private.is_platform_administrator()));
create policy depreciation_lines_insert_administrators on public.fixed_asset_depreciation_lines for insert to authenticated with check((select private.is_platform_administrator()));

create function private.protect_fixed_asset_financial_fields() returns trigger language plpgsql security invoker set search_path='' as $$
begin
 if old.academy_id<>new.academy_id or old.asset_code<>new.asset_code or old.acquired_on<>new.acquired_on or old.in_service_on<>new.in_service_on or old.currency<>new.currency or old.purchase_cost_minor<>new.purchase_cost_minor or old.residual_value_minor<>new.residual_value_minor or old.useful_life_months<>new.useful_life_months or old.asset_account_id<>new.asset_account_id or old.accumulated_depreciation_account_id<>new.accumulated_depreciation_account_id or old.depreciation_expense_account_id<>new.depreciation_expense_account_id or (old.acquisition_entry_id is not null and old.acquisition_entry_id is distinct from new.acquisition_entry_id) then raise exception 'fixed asset financial terms are immutable' using errcode='23514';end if;return new;
end;$$;
create trigger protect_fixed_asset_financial_fields before update on public.fixed_assets for each row execute function private.protect_fixed_asset_financial_fields();
create function private.protect_fixed_asset_depreciation_history() returns trigger language plpgsql security invoker set search_path='' as $$
begin
 if tg_table_name='fixed_asset_depreciation_runs' and tg_op='UPDATE' and old.journal_entry_id is null and new.journal_entry_id is not null and old.id=new.id and old.academy_id=new.academy_id and old.period_end=new.period_end and old.currency=new.currency and old.created_by=new.created_by and old.created_at=new.created_at then return new;end if;
 raise exception 'depreciation history is immutable' using errcode='23514';
end;$$;
create trigger protect_depreciation_runs before update or delete on public.fixed_asset_depreciation_runs for each row execute function private.protect_fixed_asset_depreciation_history();
create trigger protect_depreciation_lines before update or delete on public.fixed_asset_depreciation_lines for each row execute function private.protect_fixed_asset_depreciation_history();

create function public.seed_fixed_asset_accounts(target_academy_id uuid) returns integer language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());added integer;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;perform public.seed_general_ledger_accounts(target_academy_id);
 insert into public.gl_accounts(academy_id,code,name,category,normal_balance,system_key,created_by)values(target_academy_id,'1200','Fixed assets','asset','debit','fixed_assets',actor),(target_academy_id,'1290','Accumulated depreciation','asset','debit','accumulated_depreciation',actor),(target_academy_id,'5300','Depreciation expense','expense','debit','depreciation_expense',actor),(target_academy_id,'5350','Asset disposal gain or loss','expense','debit','asset_disposal_gain_loss',actor)on conflict(academy_id,code)do nothing;get diagnostics added=row_count;return added;end;$$;

create function public.register_fixed_asset(target_academy_id uuid,target_asset_code text,target_name text,target_category public.fixed_asset_category,target_acquired_on date,target_in_service_on date,target_currency text,target_purchase_cost_minor bigint,target_residual_value_minor bigint,target_useful_life_months integer,target_funding_account_id uuid,target_linked_horse_id uuid default null)
returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());normalized_currency text:=upper(btrim(target_currency));asset_id uuid;fixed_id uuid;accumulated_id uuid;expense_id uuid;entry_id uuid;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;perform public.seed_fixed_asset_accounts(target_academy_id);
 if target_asset_code!~'^[A-Za-z0-9][A-Za-z0-9._-]{1,39}$' or char_length(btrim(target_name))not between 2 and 160 or target_acquired_on is null or target_in_service_on<target_acquired_on or normalized_currency!~'^[A-Z]{3}$' or target_purchase_cost_minor<=0 or target_residual_value_minor<0 or target_residual_value_minor>=target_purchase_cost_minor or target_useful_life_months not between 1 and 600 then raise exception 'invalid fixed asset' using errcode='22023';end if;
 if not exists(select 1 from public.gl_accounts where id=target_funding_account_id and academy_id=target_academy_id and active and category in('asset','liability','equity')) then raise exception 'valid funding account required' using errcode='23514';end if;
 if target_linked_horse_id is not null and not exists(select 1 from public.horses where id=target_linked_horse_id and academy_id=target_academy_id)then raise exception 'academy horse required' using errcode='23514';end if;
 select id into fixed_id from public.gl_accounts where academy_id=target_academy_id and system_key='fixed_assets';select id into accumulated_id from public.gl_accounts where academy_id=target_academy_id and system_key='accumulated_depreciation';select id into expense_id from public.gl_accounts where academy_id=target_academy_id and system_key='depreciation_expense';
 insert into public.fixed_assets(academy_id,asset_code,name,category,linked_horse_id,acquired_on,in_service_on,currency,purchase_cost_minor,residual_value_minor,useful_life_months,asset_account_id,accumulated_depreciation_account_id,depreciation_expense_account_id,created_by,updated_by)values(target_academy_id,upper(target_asset_code),btrim(target_name),target_category,target_linked_horse_id,target_acquired_on,target_in_service_on,normalized_currency,target_purchase_cost_minor,target_residual_value_minor,target_useful_life_months,fixed_id,accumulated_id,expense_id,actor,actor)returning id into asset_id;
 entry_id:=public.post_general_ledger_entry(target_academy_id,target_acquired_on,normalized_currency,'ASSET-'||upper(target_asset_code),'Acquire fixed asset: '||btrim(target_name),jsonb_build_array(jsonb_build_object('account_id',fixed_id,'debit_minor',target_purchase_cost_minor,'credit_minor',0),jsonb_build_object('account_id',target_funding_account_id,'debit_minor',0,'credit_minor',target_purchase_cost_minor)),'fixed_asset_acquisition',asset_id);update public.fixed_assets set acquisition_entry_id=entry_id,updated_at=now() where id=asset_id;
 perform public.write_audit_event(target_academy_id,'fixed_asset.registered','fixed_asset',asset_id,jsonb_build_object('asset_code',upper(target_asset_code),'purchase_cost_minor',target_purchase_cost_minor,'currency',normalized_currency,'useful_life_months',target_useful_life_months));return asset_id;end;$$;

create function public.generate_fixed_asset_depreciation(target_academy_id uuid,target_period_end date,target_currency text) returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());normalized_currency text:=upper(btrim(target_currency));run_id uuid;entry_id uuid;total_minor bigint:=0;item public.fixed_assets%rowtype;elapsed_months integer;required_minor bigint;charge_minor bigint;expense_id uuid;accumulated_id uuid;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;if target_period_end is null or target_period_end<>(date_trunc('month',target_period_end)+interval '1 month - 1 day')::date or normalized_currency!~'^[A-Z]{3}$' then raise exception 'month-end depreciation date required' using errcode='22023';end if;perform pg_advisory_xact_lock(hashtextextended(target_academy_id::text||normalized_currency||target_period_end::text,0));select id into run_id from public.fixed_asset_depreciation_runs where academy_id=target_academy_id and currency=normalized_currency and period_end=target_period_end;if found then return run_id;end if;perform public.seed_fixed_asset_accounts(target_academy_id);select id into expense_id from public.gl_accounts where academy_id=target_academy_id and system_key='depreciation_expense';select id into accumulated_id from public.gl_accounts where academy_id=target_academy_id and system_key='accumulated_depreciation';
 insert into public.fixed_asset_depreciation_runs(academy_id,period_end,currency,total_depreciation_minor,created_by)values(target_academy_id,target_period_end,normalized_currency,1,actor)returning id into run_id;
 for item in select * from public.fixed_assets where academy_id=target_academy_id and currency=normalized_currency and status='active' and in_service_on<=target_period_end for update loop elapsed_months:=least(item.useful_life_months,greatest(0,(extract(year from target_period_end)::integer*12+extract(month from target_period_end)::integer)-(extract(year from item.in_service_on)::integer*12+extract(month from item.in_service_on)::integer)+1));required_minor:=((item.purchase_cost_minor-item.residual_value_minor)*elapsed_months/item.useful_life_months)::bigint;charge_minor:=required_minor-item.accumulated_depreciation_minor;if charge_minor>0 then insert into public.fixed_asset_depreciation_lines(run_id,academy_id,asset_id,opening_accumulated_minor,depreciation_minor,closing_accumulated_minor)values(run_id,target_academy_id,item.id,item.accumulated_depreciation_minor,charge_minor,required_minor);total_minor:=total_minor+charge_minor;end if;end loop;
 if total_minor<=0 then raise exception 'no depreciation is due for this period' using errcode='23514';end if;
 entry_id:=public.post_general_ledger_entry(target_academy_id,target_period_end,normalized_currency,'DEP-'||to_char(target_period_end,'YYYYMM'),'Monthly fixed asset depreciation',jsonb_build_array(jsonb_build_object('account_id',expense_id,'debit_minor',total_minor,'credit_minor',0),jsonb_build_object('account_id',accumulated_id,'debit_minor',0,'credit_minor',total_minor)),'fixed_asset_depreciation_run',run_id);update public.fixed_asset_depreciation_runs set total_depreciation_minor=total_minor,journal_entry_id=entry_id where id=run_id;
 update public.fixed_assets asset set accumulated_depreciation_minor=line.closing_accumulated_minor,status=case when line.closing_accumulated_minor>=asset.purchase_cost_minor-asset.residual_value_minor then 'fully_depreciated'::public.fixed_asset_status else asset.status end,updated_by=actor,updated_at=now() from public.fixed_asset_depreciation_lines line where line.run_id=run_id and line.asset_id=asset.id;
 perform public.write_audit_event(target_academy_id,'fixed_asset.depreciation_posted','fixed_asset_depreciation_run',run_id,jsonb_build_object('period_end',target_period_end,'currency',normalized_currency,'total_depreciation_minor',total_minor));return run_id;end;$$;

create function public.dispose_fixed_asset(target_asset_id uuid,target_disposal_date date,target_proceeds_minor bigint,target_reason text) returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());asset public.fixed_assets%rowtype;cash_id uuid;gain_loss_id uuid;entry_id uuid;book_value bigint;difference bigint;lines jsonb:='[]'::jsonb;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;select * into asset from public.fixed_assets where id=target_asset_id for update;if not found or asset.status='disposed' then raise exception 'active fixed asset required' using errcode='23514';end if;if target_disposal_date<asset.in_service_on or target_proceeds_minor<0 or char_length(btrim(target_reason))not between 2 and 240 then raise exception 'invalid fixed asset disposal' using errcode='22023';end if;perform public.seed_fixed_asset_accounts(asset.academy_id);select id into cash_id from public.gl_accounts where academy_id=asset.academy_id and system_key='cash';select id into gain_loss_id from public.gl_accounts where academy_id=asset.academy_id and system_key='asset_disposal_gain_loss';book_value:=asset.purchase_cost_minor-asset.accumulated_depreciation_minor;difference:=target_proceeds_minor-book_value;
 if target_proceeds_minor>0 then lines:=lines||jsonb_build_array(jsonb_build_object('account_id',cash_id,'debit_minor',target_proceeds_minor,'credit_minor',0));end if;if asset.accumulated_depreciation_minor>0 then lines:=lines||jsonb_build_array(jsonb_build_object('account_id',asset.accumulated_depreciation_account_id,'debit_minor',asset.accumulated_depreciation_minor,'credit_minor',0));end if;lines:=lines||jsonb_build_array(jsonb_build_object('account_id',asset.asset_account_id,'debit_minor',0,'credit_minor',asset.purchase_cost_minor));if difference>0 then lines:=lines||jsonb_build_array(jsonb_build_object('account_id',gain_loss_id,'debit_minor',0,'credit_minor',difference));elsif difference<0 then lines:=lines||jsonb_build_array(jsonb_build_object('account_id',gain_loss_id,'debit_minor',-difference,'credit_minor',0));end if;
 entry_id:=public.post_general_ledger_entry(asset.academy_id,target_disposal_date,asset.currency,'DISP-'||asset.asset_code,'Dispose fixed asset: '||btrim(target_reason),lines,'fixed_asset_disposal',asset.id);update public.fixed_assets set status='disposed',disposal_date=target_disposal_date,disposal_proceeds_minor=target_proceeds_minor,disposal_gain_loss_minor=difference,disposal_entry_id=entry_id,disposal_reason=btrim(target_reason),updated_by=actor,updated_at=now() where id=asset.id;
 perform public.write_audit_event(asset.academy_id,'fixed_asset.disposed','fixed_asset',asset.id,jsonb_build_object('disposal_date',target_disposal_date,'proceeds_minor',target_proceeds_minor,'gain_loss_minor',difference,'currency',asset.currency));return entry_id;end;$$;

revoke all on function public.seed_fixed_asset_accounts(uuid),public.register_fixed_asset(uuid,text,text,public.fixed_asset_category,date,date,text,bigint,bigint,integer,uuid,uuid),public.generate_fixed_asset_depreciation(uuid,date,text),public.dispose_fixed_asset(uuid,date,bigint,text) from public,anon,authenticated;
grant execute on function public.seed_fixed_asset_accounts(uuid),public.register_fixed_asset(uuid,text,text,public.fixed_asset_category,date,date,text,bigint,bigint,integer,uuid,uuid),public.generate_fixed_asset_depreciation(uuid,date,text),public.dispose_fixed_asset(uuid,date,bigint,text) to authenticated;
revoke all on function private.protect_fixed_asset_financial_fields(),private.protect_fixed_asset_depreciation_history() from public,anon,authenticated;

commit;
