begin;

create or replace function public.generate_fixed_asset_depreciation(target_academy_id uuid,target_period_end date,target_currency text) returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());normalized_currency text:=upper(btrim(target_currency));generated_run_id uuid;entry_id uuid;total_minor bigint:=0;item public.fixed_assets%rowtype;elapsed_months integer;required_minor bigint;charge_minor bigint;expense_id uuid;accumulated_id uuid;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;if target_period_end is null or target_period_end<>(date_trunc('month',target_period_end)+interval '1 month - 1 day')::date or normalized_currency!~'^[A-Z]{3}$' then raise exception 'month-end depreciation date required' using errcode='22023';end if;perform pg_advisory_xact_lock(hashtextextended(target_academy_id::text||normalized_currency||target_period_end::text,0));select id into generated_run_id from public.fixed_asset_depreciation_runs where academy_id=target_academy_id and currency=normalized_currency and period_end=target_period_end;if found then return generated_run_id;end if;perform public.seed_fixed_asset_accounts(target_academy_id);select id into expense_id from public.gl_accounts where academy_id=target_academy_id and system_key='depreciation_expense';select id into accumulated_id from public.gl_accounts where academy_id=target_academy_id and system_key='accumulated_depreciation';
 insert into public.fixed_asset_depreciation_runs(academy_id,period_end,currency,total_depreciation_minor,created_by)values(target_academy_id,target_period_end,normalized_currency,1,actor)returning id into generated_run_id;
 for item in select * from public.fixed_assets where academy_id=target_academy_id and currency=normalized_currency and status='active' and in_service_on<=target_period_end for update loop elapsed_months:=least(item.useful_life_months,greatest(0,(extract(year from target_period_end)::integer*12+extract(month from target_period_end)::integer)-(extract(year from item.in_service_on)::integer*12+extract(month from item.in_service_on)::integer)+1));required_minor:=((item.purchase_cost_minor-item.residual_value_minor)*elapsed_months/item.useful_life_months)::bigint;charge_minor:=required_minor-item.accumulated_depreciation_minor;if charge_minor>0 then insert into public.fixed_asset_depreciation_lines(run_id,academy_id,asset_id,opening_accumulated_minor,depreciation_minor,closing_accumulated_minor)values(generated_run_id,target_academy_id,item.id,item.accumulated_depreciation_minor,charge_minor,required_minor);total_minor:=total_minor+charge_minor;end if;end loop;
 if total_minor<=0 then raise exception 'no depreciation is due for this period' using errcode='23514';end if;
 entry_id:=public.post_general_ledger_entry(target_academy_id,target_period_end,normalized_currency,'DEP-'||to_char(target_period_end,'YYYYMM'),'Monthly fixed asset depreciation',jsonb_build_array(jsonb_build_object('account_id',expense_id,'debit_minor',total_minor,'credit_minor',0),jsonb_build_object('account_id',accumulated_id,'debit_minor',0,'credit_minor',total_minor)),'fixed_asset_depreciation_run',generated_run_id);update public.fixed_asset_depreciation_runs set total_depreciation_minor=total_minor,journal_entry_id=entry_id where id=generated_run_id;
 update public.fixed_assets asset set accumulated_depreciation_minor=line.closing_accumulated_minor,status=case when line.closing_accumulated_minor>=asset.purchase_cost_minor-asset.residual_value_minor then 'fully_depreciated'::public.fixed_asset_status else asset.status end,updated_by=actor,updated_at=now() from public.fixed_asset_depreciation_lines line where line.run_id=generated_run_id and line.asset_id=asset.id;
 perform public.write_audit_event(target_academy_id,'fixed_asset.depreciation_posted','fixed_asset_depreciation_run',generated_run_id,jsonb_build_object('period_end',target_period_end,'currency',normalized_currency,'total_depreciation_minor',total_minor));return generated_run_id;end;$$;

revoke all on function public.generate_fixed_asset_depreciation(uuid,date,text) from public,anon,authenticated;
grant execute on function public.generate_fixed_asset_depreciation(uuid,date,text) to authenticated;

commit;
