begin;

create type public.gl_account_category as enum ('asset','liability','equity','revenue','expense');
create type public.gl_normal_balance as enum ('debit','credit');
create type public.gl_entry_status as enum ('draft','posted','reversed');

create table public.gl_accounts(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,
 code text not null,name text not null,category public.gl_account_category not null,normal_balance public.gl_normal_balance not null,
 parent_id uuid references public.gl_accounts(id) on delete restrict,system_key text,active boolean not null default true,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint gl_account_code_length check(char_length(code) between 2 and 20),constraint gl_account_name_length check(char_length(name) between 2 and 120),
 constraint gl_account_system_key check(system_key is null or system_key~'^[a-z][a-z0-9_]{1,39}$'),unique(academy_id,code),unique(academy_id,system_key)
);
create table public.gl_journal_entries(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,
 entry_date date not null,currency text not null check(currency~'^[A-Z]{3}$'),reference text not null,description text not null,
 status public.gl_entry_status not null default 'draft',source_type text,source_id uuid,reversal_of_entry_id uuid unique references public.gl_journal_entries(id) on delete restrict,
 created_by uuid not null references auth.users(id),posted_by uuid references auth.users(id),posted_at timestamptz,reversed_by uuid references auth.users(id),reversed_at timestamptz,created_at timestamptz not null default now(),
 constraint gl_entry_reference_length check(char_length(reference) between 1 and 80),constraint gl_entry_description_length check(char_length(description) between 2 and 500),
 constraint gl_entry_source_pair check((source_type is null)=(source_id is null)),constraint gl_entry_source_length check(source_type is null or source_type~'^[a-z][a-z0-9_]{1,49}$'),
 constraint gl_entry_post_state check((status='draft' and posted_by is null and posted_at is null) or (status in('posted','reversed') and posted_by is not null and posted_at is not null)),
 constraint gl_entry_reverse_state check((status='reversed')=(reversed_by is not null and reversed_at is not null))
);
create unique index gl_entries_source_unique_idx on public.gl_journal_entries(academy_id,source_type,source_id) where source_id is not null;
create table public.gl_journal_lines(
 id uuid primary key default gen_random_uuid(),journal_entry_id uuid not null references public.gl_journal_entries(id) on delete restrict,
 academy_id uuid not null references public.academies(id) on delete restrict,account_id uuid not null references public.gl_accounts(id) on delete restrict,line_number smallint not null,
 description text,debit_minor bigint not null default 0,credit_minor bigint not null default 0,created_at timestamptz not null default now(),
 constraint gl_line_number_positive check(line_number>0),constraint gl_line_description_length check(description is null or char_length(description) between 2 and 240),
 constraint gl_line_one_side check((debit_minor>0 and credit_minor=0) or (credit_minor>0 and debit_minor=0)),unique(journal_entry_id,line_number)
);
create index gl_accounts_academy_active_idx on public.gl_accounts(academy_id,active,code);create index gl_accounts_parent_idx on public.gl_accounts(parent_id) where parent_id is not null;create index gl_accounts_created_by_idx on public.gl_accounts(created_by);
create index gl_entries_academy_date_idx on public.gl_journal_entries(academy_id,currency,entry_date desc);create index gl_entries_created_by_idx on public.gl_journal_entries(created_by);create index gl_entries_posted_by_idx on public.gl_journal_entries(posted_by) where posted_by is not null;create index gl_entries_reversed_by_idx on public.gl_journal_entries(reversed_by) where reversed_by is not null;
create index gl_lines_entry_idx on public.gl_journal_lines(journal_entry_id);create index gl_lines_academy_account_idx on public.gl_journal_lines(academy_id,account_id);

alter table public.gl_accounts enable row level security;alter table public.gl_journal_entries enable row level security;alter table public.gl_journal_lines enable row level security;
revoke all on public.gl_accounts,public.gl_journal_entries,public.gl_journal_lines from public,anon,authenticated;
grant select,insert,update on public.gl_accounts,public.gl_journal_entries to authenticated;grant select,insert on public.gl_journal_lines to authenticated;
grant select,insert,update,delete on public.gl_accounts,public.gl_journal_entries,public.gl_journal_lines to service_role;
grant usage on type public.gl_account_category,public.gl_normal_balance,public.gl_entry_status to authenticated;
create policy gl_accounts_read_administrators on public.gl_accounts for select to authenticated using((select private.is_platform_administrator()));
create policy gl_accounts_insert_administrators on public.gl_accounts for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));
create policy gl_accounts_update_administrators on public.gl_accounts for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy gl_entries_read_administrators on public.gl_journal_entries for select to authenticated using((select private.is_platform_administrator()));
create policy gl_entries_insert_administrators on public.gl_journal_entries for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));
create policy gl_entries_update_administrators on public.gl_journal_entries for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy gl_lines_read_administrators on public.gl_journal_lines for select to authenticated using((select private.is_platform_administrator()));
create policy gl_lines_insert_administrators on public.gl_journal_lines for insert to authenticated with check((select private.is_platform_administrator()));

create function private.validate_gl_entry_status() returns trigger language plpgsql security invoker set search_path='' as $$
declare debits bigint;credits bigint;line_count integer;
begin
 if tg_op='UPDATE' then
  if old.status in('posted','reversed') and new.status<>(case when old.status='posted' then 'reversed'::public.gl_entry_status else old.status end) then raise exception 'posted journal entries are immutable' using errcode='23514';end if;
 end if;
 if new.status='posted' and (tg_op='INSERT' or (tg_op='UPDATE' and old.status='draft')) then
  select count(*),coalesce(sum(debit_minor),0),coalesce(sum(credit_minor),0) into line_count,debits,credits from public.gl_journal_lines where journal_entry_id=new.id;
  if line_count<2 or debits<=0 or debits<>credits then raise exception 'journal entry must contain at least two balanced lines' using errcode='23514';end if;
 end if;return new;
end;$$;
create trigger validate_gl_entry_status before insert or update on public.gl_journal_entries for each row execute function private.validate_gl_entry_status();
create function private.protect_posted_gl_lines() returns trigger language plpgsql security invoker set search_path='' as $$
declare entry_status public.gl_entry_status;
begin select status into entry_status from public.gl_journal_entries where id=coalesce(new.journal_entry_id,old.journal_entry_id);if entry_status<>'draft' then raise exception 'posted journal lines are immutable' using errcode='23514';end if;return coalesce(new,old);end;$$;
create trigger protect_posted_gl_lines before insert or update or delete on public.gl_journal_lines for each row execute function private.protect_posted_gl_lines();

create function public.seed_general_ledger_accounts(target_academy_id uuid) returns integer language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());added integer;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;
 insert into public.gl_accounts(academy_id,code,name,category,normal_balance,system_key,created_by) values
 (target_academy_id,'1000','Cash and bank','asset','debit','cash',actor),(target_academy_id,'1100','Accounts receivable','asset','debit','accounts_receivable',actor),(target_academy_id,'2000','Accounts payable','liability','credit','accounts_payable',actor),(target_academy_id,'3000','Owner equity','equity','credit','owner_equity',actor),(target_academy_id,'4000','Membership revenue','revenue','credit','membership_revenue',actor),(target_academy_id,'5000','Supplier expense','expense','debit','supplier_expense',actor),(target_academy_id,'5100','Payroll expense','expense','debit','payroll_expense',actor),(target_academy_id,'5200','Operating expense','expense','debit','operating_expense',actor),(target_academy_id,'9999','Suspense','asset','debit','suspense',actor)
 on conflict(academy_id,code) do nothing;get diagnostics added=row_count;
 perform public.write_audit_event(target_academy_id,'general_ledger.accounts_seeded','gl_account',null,jsonb_build_object('accounts_added',added));return added;end;$$;

create function public.post_general_ledger_entry(target_academy_id uuid,target_entry_date date,target_currency text,target_reference text,target_description text,target_lines jsonb,target_source_type text default null,target_source_id uuid default null)
returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());entry_id uuid;normalized_currency text:=upper(btrim(target_currency));debits bigint;credits bigint;line_count integer;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;
 if target_entry_date is null or normalized_currency!~'^[A-Z]{3}$' or char_length(btrim(target_reference)) not between 1 and 80 or char_length(btrim(target_description)) not between 2 and 500 or jsonb_typeof(target_lines)<>'array' or jsonb_array_length(target_lines) not between 2 and 100 or ((target_source_type is null)<>(target_source_id is null)) then raise exception 'invalid journal entry' using errcode='22023';end if;
 if exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',target_entry_date)::date and close.status='closed') then raise exception 'financial period is closed' using errcode='23514';end if;
 if target_source_id is not null then perform pg_advisory_xact_lock(hashtextextended(target_academy_id::text||target_source_type||target_source_id::text,0));select id into entry_id from public.gl_journal_entries where academy_id=target_academy_id and source_type=target_source_type and source_id=target_source_id;if found then return entry_id;end if;end if;
 with parsed as(select * from jsonb_to_recordset(target_lines) as x(account_id uuid,debit_minor bigint,credit_minor bigint,description text)) select count(*),coalesce(sum(debit_minor),0),coalesce(sum(credit_minor),0) into line_count,debits,credits from parsed;
 if line_count<2 or debits<=0 or debits<>credits or exists(select 1 from jsonb_to_recordset(target_lines) as x(account_id uuid,debit_minor bigint,credit_minor bigint,description text) left join public.gl_accounts account on account.id=x.account_id and account.academy_id=target_academy_id and account.active where account.id is null or not((x.debit_minor>0 and x.credit_minor=0) or(x.credit_minor>0 and x.debit_minor=0))) then raise exception 'journal lines must be active, scoped and balanced' using errcode='23514';end if;
 insert into public.gl_journal_entries(academy_id,entry_date,currency,reference,description,source_type,source_id,created_by) values(target_academy_id,target_entry_date,normalized_currency,btrim(target_reference),btrim(target_description),target_source_type,target_source_id,actor) returning id into entry_id;
 insert into public.gl_journal_lines(journal_entry_id,academy_id,account_id,line_number,description,debit_minor,credit_minor) select entry_id,target_academy_id,x.account_id,row_number()over()::smallint,nullif(btrim(x.description),''),x.debit_minor,x.credit_minor from jsonb_to_recordset(target_lines) as x(account_id uuid,debit_minor bigint,credit_minor bigint,description text);
 update public.gl_journal_entries set status='posted',posted_by=actor,posted_at=now() where id=entry_id;
 perform public.write_audit_event(target_academy_id,'general_ledger.entry_posted','gl_journal_entry',entry_id,jsonb_build_object('entry_date',target_entry_date,'currency',normalized_currency,'debits_minor',debits,'reference',btrim(target_reference),'source_type',target_source_type));return entry_id;end;$$;

create function public.reverse_general_ledger_entry(target_entry_id uuid,target_reversal_date date,target_reason text) returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());scoped public.gl_journal_entries%rowtype;reversal_id uuid;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;if char_length(btrim(target_reason)) not between 2 and 240 then raise exception 'reversal reason required' using errcode='22023';end if;
 select * into scoped from public.gl_journal_entries where id=target_entry_id for update;if not found or scoped.status<>'posted' then raise exception 'posted journal entry required' using errcode='23514';end if;
 if target_reversal_date<scoped.entry_date or exists(select 1 from public.financial_close_periods close where close.academy_id=scoped.academy_id and close.currency=scoped.currency and close.month_start=date_trunc('month',target_reversal_date)::date and close.status='closed') then raise exception 'reversal date must be in an open period' using errcode='23514';end if;
 insert into public.gl_journal_entries(academy_id,entry_date,currency,reference,description,reversal_of_entry_id,created_by) values(scoped.academy_id,target_reversal_date,scoped.currency,'REV-'||scoped.reference,'Reversal: '||btrim(target_reason),scoped.id,actor) returning id into reversal_id;
 insert into public.gl_journal_lines(journal_entry_id,academy_id,account_id,line_number,description,debit_minor,credit_minor) select reversal_id,academy_id,account_id,line_number,description,credit_minor,debit_minor from public.gl_journal_lines where journal_entry_id=scoped.id order by line_number;
 update public.gl_journal_entries set status='posted',posted_by=actor,posted_at=now() where id=reversal_id;update public.gl_journal_entries set status='reversed',reversed_by=actor,reversed_at=now() where id=scoped.id;
 perform public.write_audit_event(scoped.academy_id,'general_ledger.entry_reversed','gl_journal_entry',scoped.id,jsonb_build_object('reversal_entry_id',reversal_id,'reversal_date',target_reversal_date,'reason',btrim(target_reason)));return reversal_id;end;$$;

create function public.get_general_ledger_trial_balance(target_academy_id uuid,target_starts_on date,target_ends_on date,target_currency text) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());result jsonb;normalized_currency text:=upper(btrim(target_currency));
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;if target_ends_on<target_starts_on or target_ends_on-target_starts_on>731 or normalized_currency!~'^[A-Z]{3}$' then raise exception 'invalid trial balance range' using errcode='22023';end if;
 with balances as(select account.id,account.code,account.name,account.category,account.normal_balance,
 coalesce(sum(case when entry.entry_date<target_starts_on then line.debit_minor-line.credit_minor else 0 end),0) opening_minor,
 coalesce(sum(case when entry.entry_date between target_starts_on and target_ends_on then line.debit_minor else 0 end),0) debit_minor,
 coalesce(sum(case when entry.entry_date between target_starts_on and target_ends_on then line.credit_minor else 0 end),0) credit_minor
 from public.gl_accounts account left join public.gl_journal_lines line on line.account_id=account.id left join public.gl_journal_entries entry on entry.id=line.journal_entry_id and entry.currency=normalized_currency and entry.entry_date<=target_ends_on and entry.status in('posted','reversed') where account.academy_id=target_academy_id group by account.id)
 select jsonb_build_object('starts_on',target_starts_on,'ends_on',target_ends_on,'currency',normalized_currency,'total_debit_minor',coalesce(sum(debit_minor),0),'total_credit_minor',coalesce(sum(credit_minor),0),'balanced',coalesce(sum(debit_minor),0)=coalesce(sum(credit_minor),0),'accounts',jsonb_agg(jsonb_build_object('id',id,'code',code,'name',name,'category',category,'normal_balance',normal_balance,'opening_minor',opening_minor,'debit_minor',debit_minor,'credit_minor',credit_minor,'closing_minor',opening_minor+debit_minor-credit_minor) order by code)) into result from balances;return result;end;$$;

create function public.sync_general_ledger_operations(target_academy_id uuid,target_starts_on date,target_ends_on date,target_currency text) returns integer language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());normalized_currency text:=upper(btrim(target_currency));cash_id uuid;ar_id uuid;revenue_id uuid;supplier_id uuid;payroll_id uuid;operating_id uuid;item record;processed integer:=0;
begin if actor is null or not private.is_platform_administrator() then raise exception 'platform administrator access required' using errcode='42501';end if;if target_ends_on<target_starts_on or target_ends_on-target_starts_on>731 then raise exception 'invalid sync range' using errcode='22023';end if;perform public.seed_general_ledger_accounts(target_academy_id);
 select id into cash_id from public.gl_accounts where academy_id=target_academy_id and system_key='cash';select id into ar_id from public.gl_accounts where academy_id=target_academy_id and system_key='accounts_receivable';select id into revenue_id from public.gl_accounts where academy_id=target_academy_id and system_key='membership_revenue';select id into supplier_id from public.gl_accounts where academy_id=target_academy_id and system_key='supplier_expense';select id into payroll_id from public.gl_accounts where academy_id=target_academy_id and system_key='payroll_expense';select id into operating_id from public.gl_accounts where academy_id=target_academy_id and system_key='operating_expense';
 for item in select invoice.id,invoice.issued_at::date event_date,invoice.invoice_number reference,invoice.description,invoice.amount_minor from public.invoices invoice where invoice.academy_id=target_academy_id and invoice.currency=normalized_currency and invoice.issued_at::date between target_starts_on and target_ends_on and invoice.status<>'void' and not exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',invoice.issued_at)::date and close.status='closed') loop perform public.post_general_ledger_entry(target_academy_id,item.event_date,normalized_currency,item.reference,item.description,jsonb_build_array(jsonb_build_object('account_id',ar_id,'debit_minor',item.amount_minor,'credit_minor',0),jsonb_build_object('account_id',revenue_id,'debit_minor',0,'credit_minor',item.amount_minor)),'customer_invoice',item.id);processed:=processed+1;end loop;
 for item in select entry.id,entry.created_at::date event_date,'PAY-'||left(entry.id::text,8) reference,entry.note description,entry.amount_minor from public.billing_ledger_entries entry where entry.academy_id=target_academy_id and entry.currency=normalized_currency and entry.entry_type='payment' and entry.amount_minor>0 and entry.created_at::date between target_starts_on and target_ends_on and not exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',entry.created_at)::date and close.status='closed') loop perform public.post_general_ledger_entry(target_academy_id,item.event_date,normalized_currency,item.reference,coalesce(item.description,'Customer payment'),jsonb_build_array(jsonb_build_object('account_id',cash_id,'debit_minor',item.amount_minor,'credit_minor',0),jsonb_build_object('account_id',ar_id,'debit_minor',0,'credit_minor',item.amount_minor)),'customer_payment',item.id);processed:=processed+1;end loop;
 for item in select expense.id,expense.incurred_at::date event_date,'EXP-'||left(expense.id::text,8) reference,expense.description,expense.amount_minor from public.cash_expenses expense where expense.academy_id=target_academy_id and expense.currency=normalized_currency and expense.incurred_at::date between target_starts_on and target_ends_on and not exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',expense.incurred_at)::date and close.status='closed') loop perform public.post_general_ledger_entry(target_academy_id,item.event_date,normalized_currency,item.reference,item.description,jsonb_build_array(jsonb_build_object('account_id',operating_id,'debit_minor',item.amount_minor,'credit_minor',0),jsonb_build_object('account_id',cash_id,'debit_minor',0,'credit_minor',item.amount_minor)),'cash_expense',item.id);processed:=processed+1;end loop;
 for item in select invoice.id,invoice.paid_at::date event_date,invoice.invoice_number reference,financial.description,financial.amount_minor from public.supplier_invoices invoice join public.supplier_invoice_financials financial on financial.invoice_id=invoice.id where invoice.academy_id=target_academy_id and financial.currency=normalized_currency and invoice.status='paid' and invoice.paid_at::date between target_starts_on and target_ends_on and not exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',invoice.paid_at)::date and close.status='closed') loop perform public.post_general_ledger_entry(target_academy_id,item.event_date,normalized_currency,item.reference,item.description,jsonb_build_array(jsonb_build_object('account_id',supplier_id,'debit_minor',item.amount_minor,'credit_minor',0),jsonb_build_object('account_id',cash_id,'debit_minor',0,'credit_minor',item.amount_minor)),'supplier_payment',item.id);processed:=processed+1;end loop;
 for item in select period.id,period.paid_at::date event_date,'PAYROLL-'||to_char(period.ends_on,'YYYYMMDD') reference,'Payroll '||period.starts_on||' to '||period.ends_on description,sum(payroll_item.amount_minor)::bigint amount_minor from public.payroll_periods period join public.payroll_items payroll_item on payroll_item.payroll_period_id=period.id where period.academy_id=target_academy_id and period.currency=normalized_currency and period.status='paid' and period.paid_at::date between target_starts_on and target_ends_on and not exists(select 1 from public.financial_close_periods close where close.academy_id=target_academy_id and close.currency=normalized_currency and close.month_start=date_trunc('month',period.paid_at)::date and close.status='closed') group by period.id loop perform public.post_general_ledger_entry(target_academy_id,item.event_date,normalized_currency,item.reference,item.description,jsonb_build_array(jsonb_build_object('account_id',payroll_id,'debit_minor',item.amount_minor,'credit_minor',0),jsonb_build_object('account_id',cash_id,'debit_minor',0,'credit_minor',item.amount_minor)),'payroll_payment',item.id);processed:=processed+1;end loop;
 perform public.write_audit_event(target_academy_id,'general_ledger.operations_synced','gl_journal_entry',null,jsonb_build_object('starts_on',target_starts_on,'ends_on',target_ends_on,'currency',normalized_currency,'sources_processed',processed));return processed;end;$$;

revoke all on function public.seed_general_ledger_accounts(uuid),public.post_general_ledger_entry(uuid,date,text,text,text,jsonb,text,uuid),public.reverse_general_ledger_entry(uuid,date,text),public.get_general_ledger_trial_balance(uuid,date,date,text),public.sync_general_ledger_operations(uuid,date,date,text) from public,anon,authenticated;
grant execute on function public.seed_general_ledger_accounts(uuid),public.post_general_ledger_entry(uuid,date,text,text,text,jsonb,text,uuid),public.reverse_general_ledger_entry(uuid,date,text),public.get_general_ledger_trial_balance(uuid,date,date,text),public.sync_general_ledger_operations(uuid,date,date,text) to authenticated;
revoke all on function private.validate_gl_entry_status(),private.protect_posted_gl_lines() from public,anon,authenticated;

commit;
