begin;

create table public.enterprise_risks(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,risk_code text not null,category text not null,title text not null,description text not null,causes text not null,consequences text not null,
 inherent_likelihood smallint not null,inherent_impact smallint not null,inherent_score smallint generated always as(inherent_likelihood*inherent_impact)stored,
 control_effectiveness text not null default 'partial',residual_likelihood smallint not null,residual_impact smallint not null,residual_score smallint generated always as(residual_likelihood*residual_impact)stored,risk_appetite_limit smallint not null default 9,
 owner_user_id uuid not null references auth.users(id),status text not null default 'active',treatment_plan text,treatment_due_on date,last_reviewed_on date,next_review_on date,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),
 constraint enterprise_risk_code_length check(char_length(risk_code)between 2 and 30),constraint enterprise_risk_category_allowed check(category in('strategic','financial','operational','compliance','technology','safety','reputation')),
 constraint enterprise_risk_title_length check(char_length(title)between 5 and 180),constraint enterprise_risk_description_length check(char_length(description)between 10 and 3000),constraint enterprise_risk_causes_length check(char_length(causes)between 5 and 2000),constraint enterprise_risk_consequences_length check(char_length(consequences)between 5 and 2000),
 constraint enterprise_risk_scores check(inherent_likelihood between 1 and 5 and inherent_impact between 1 and 5 and residual_likelihood between 1 and 5 and residual_impact between 1 and 5 and risk_appetite_limit between 1 and 25),
 constraint enterprise_risk_effectiveness check(control_effectiveness in('weak','partial','strong')),constraint enterprise_risk_status check(status in('draft','active','treating','accepted','closed')),
 constraint enterprise_risk_treatment check((status<>'treating')or(char_length(treatment_plan)between 10 and 3000 and treatment_due_on is not null)),constraint enterprise_risk_review_dates check(next_review_on is null or last_reviewed_on is null or next_review_on>=last_reviewed_on),unique(academy_id,risk_code)
);

create table public.risk_control_mappings(
 id uuid primary key default gen_random_uuid(),risk_id uuid not null references public.enterprise_risks(id) on delete restrict,control_id uuid not null references public.audit_control_definitions(id) on delete restrict,reliance text not null,notes text not null,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),constraint risk_control_reliance check(reliance in('primary','supporting')),constraint risk_control_notes_length check(char_length(notes)between 5 and 2000),unique(risk_id,control_id)
);

create table public.enterprise_risk_reviews(
 id uuid primary key default gen_random_uuid(),risk_id uuid not null references public.enterprise_risks(id) on delete restrict,reviewed_on date not null default current_date,inherent_likelihood smallint not null,inherent_impact smallint not null,residual_likelihood smallint not null,residual_impact smallint not null,control_effectiveness text not null,review_notes text not null,evidence_references jsonb not null default '[]'::jsonb,reviewed_by uuid not null references auth.users(id),created_at timestamptz not null default now(),
 constraint risk_review_scores check(inherent_likelihood between 1 and 5 and inherent_impact between 1 and 5 and residual_likelihood between 1 and 5 and residual_impact between 1 and 5),constraint risk_review_effectiveness check(control_effectiveness in('weak','partial','strong')),constraint risk_review_notes_length check(char_length(review_notes)between 10 and 3000),constraint risk_review_evidence_array check(jsonb_typeof(evidence_references)='array')
);

create table public.internal_audit_plan_engagements(
 id uuid primary key default gen_random_uuid(),academy_id uuid not null references public.academies(id) on delete restrict,plan_year smallint not null,risk_id uuid references public.enterprise_risks(id) on delete restrict,title text not null,objective text not null,scope text not null,priority text not null,lead_user_id uuid not null references auth.users(id),planned_start_on date not null,planned_end_on date not null,budget_hours integer not null,actual_hours integer not null default 0,status text not null default 'planned',conclusion text,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),
 constraint audit_plan_year check(plan_year between 2020 and 2100),constraint audit_plan_title_length check(char_length(title)between 5 and 180),constraint audit_plan_objective_length check(char_length(objective)between 10 and 3000),constraint audit_plan_scope_length check(char_length(scope)between 10 and 3000),constraint audit_plan_priority check(priority in('low','medium','high','critical')),constraint audit_plan_dates check(planned_end_on>=planned_start_on and extract(year from planned_start_on)=plan_year),constraint audit_plan_hours check(budget_hours between 1 and 10000 and actual_hours between 0 and 10000),constraint audit_plan_status check(status in('planned','in_progress','reporting','completed','cancelled')),constraint audit_plan_completion check(status<>'completed'or char_length(conclusion)between 10 and 4000),unique(academy_id,plan_year,title)
);

create index enterprise_risks_academy_status_idx on public.enterprise_risks(academy_id,status,residual_score desc);create index enterprise_risks_owner_idx on public.enterprise_risks(owner_user_id,status);create index enterprise_risks_review_idx on public.enterprise_risks(next_review_on)where status not in('closed');create index enterprise_risks_created_by_idx on public.enterprise_risks(created_by);create index enterprise_risks_updated_by_idx on public.enterprise_risks(updated_by);
create index risk_control_control_idx on public.risk_control_mappings(control_id);create index risk_control_created_by_idx on public.risk_control_mappings(created_by);create index risk_reviews_risk_date_idx on public.enterprise_risk_reviews(risk_id,reviewed_on desc);create index risk_reviews_reviewer_idx on public.enterprise_risk_reviews(reviewed_by);
create index audit_plan_academy_year_idx on public.internal_audit_plan_engagements(academy_id,plan_year,status);create index audit_plan_risk_idx on public.internal_audit_plan_engagements(risk_id)where risk_id is not null;create index audit_plan_lead_idx on public.internal_audit_plan_engagements(lead_user_id,status);create index audit_plan_created_by_idx on public.internal_audit_plan_engagements(created_by);create index audit_plan_updated_by_idx on public.internal_audit_plan_engagements(updated_by);

alter table public.enterprise_risks enable row level security;alter table public.risk_control_mappings enable row level security;alter table public.enterprise_risk_reviews enable row level security;alter table public.internal_audit_plan_engagements enable row level security;
revoke all on public.enterprise_risks,public.risk_control_mappings,public.enterprise_risk_reviews,public.internal_audit_plan_engagements from public,anon,authenticated;
grant select,insert,update on public.enterprise_risks,public.internal_audit_plan_engagements to authenticated;grant select,insert on public.risk_control_mappings,public.enterprise_risk_reviews to authenticated;
grant select,insert,update,delete on public.enterprise_risks,public.risk_control_mappings,public.enterprise_risk_reviews,public.internal_audit_plan_engagements to service_role;
create policy enterprise_risks_read_admin on public.enterprise_risks for select to authenticated using((select private.is_platform_administrator()));create policy enterprise_risks_insert_admin on public.enterprise_risks for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid())and updated_by=(select auth.uid()));create policy enterprise_risks_update_admin on public.enterprise_risks for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));
create policy risk_control_read_admin on public.risk_control_mappings for select to authenticated using((select private.is_platform_administrator()));create policy risk_control_insert_admin on public.risk_control_mappings for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid()));
create policy risk_reviews_read_admin on public.enterprise_risk_reviews for select to authenticated using((select private.is_platform_administrator()));create policy risk_reviews_insert_admin on public.enterprise_risk_reviews for insert to authenticated with check((select private.is_platform_administrator())and reviewed_by=(select auth.uid()));
create policy audit_plan_read_admin on public.internal_audit_plan_engagements for select to authenticated using((select private.is_platform_administrator()));create policy audit_plan_insert_admin on public.internal_audit_plan_engagements for insert to authenticated with check((select private.is_platform_administrator())and created_by=(select auth.uid())and updated_by=(select auth.uid()));create policy audit_plan_update_admin on public.internal_audit_plan_engagements for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));

create function private.protect_closed_enterprise_risk()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status='closed'then raise exception 'closed risk is immutable' using errcode='23514';end if;new.updated_at:=now();return new;end;$$;
create trigger protect_closed_enterprise_risk before update or delete on public.enterprise_risks for each row execute function private.protect_closed_enterprise_risk();
create function private.protect_risk_review()returns trigger language plpgsql security invoker set search_path='' as $$begin raise exception 'risk review is immutable' using errcode='23514';end;$$;
create trigger protect_risk_review before update or delete on public.enterprise_risk_reviews for each row execute function private.protect_risk_review();
create function private.protect_completed_audit_engagement()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status in('completed','cancelled')then raise exception 'terminal audit engagement is immutable' using errcode='23514';end if;new.updated_at:=now();return new;end;$$;
create trigger protect_completed_audit_engagement before update or delete on public.internal_audit_plan_engagements for each row execute function private.protect_completed_audit_engagement();

create function public.create_enterprise_risk(target_academy_id uuid,target_risk_code text,target_category text,target_title text,target_description text,target_causes text,target_consequences text,target_inherent_likelihood smallint,target_inherent_impact smallint,target_residual_likelihood smallint,target_residual_impact smallint,target_risk_appetite_limit smallint,target_owner_user_id uuid)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;if not exists(select 1 from public.academies where id=target_academy_id and archived_at is null)or not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')then raise exception 'active academy and owner required' using errcode='23514';end if;insert into public.enterprise_risks(academy_id,risk_code,category,title,description,causes,consequences,inherent_likelihood,inherent_impact,residual_likelihood,residual_impact,risk_appetite_limit,owner_user_id,created_by,updated_by)values(target_academy_id,upper(btrim(target_risk_code)),target_category,btrim(target_title),btrim(target_description),btrim(target_causes),btrim(target_consequences),target_inherent_likelihood,target_inherent_impact,target_residual_likelihood,target_residual_impact,target_risk_appetite_limit,target_owner_user_id,actor,actor)returning id into created_id;perform public.write_audit_event(target_academy_id,'risk.created','enterprise_risk',created_id,jsonb_build_object('risk_code',upper(btrim(target_risk_code))));return created_id;end;$$;
create function public.update_enterprise_risk(target_risk_id uuid,target_status text,target_control_effectiveness text,target_residual_likelihood smallint,target_residual_impact smallint,target_risk_appetite_limit smallint,target_owner_user_id uuid,target_treatment_plan text,target_treatment_due_on date)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.enterprise_risks%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.enterprise_risks where id=target_risk_id for update;if scoped.id is null then raise exception 'active risk required' using errcode='P0002';end if;if not exists(select 1 from public.platform_access where user_id=target_owner_user_id and status='active')then raise exception 'active owner required' using errcode='23514';end if;update public.enterprise_risks set status=target_status,control_effectiveness=target_control_effectiveness,residual_likelihood=target_residual_likelihood,residual_impact=target_residual_impact,risk_appetite_limit=target_risk_appetite_limit,owner_user_id=target_owner_user_id,treatment_plan=nullif(btrim(coalesce(target_treatment_plan,'')),''),treatment_due_on=target_treatment_due_on,updated_by=actor where id=scoped.id;perform public.write_audit_event(scoped.academy_id,'risk.updated','enterprise_risk',scoped.id,jsonb_build_object('status',target_status,'residual_score',target_residual_likelihood*target_residual_impact));return true;end;$$;
create function public.map_risk_control(target_risk_id uuid,target_control_id uuid,target_reliance text,target_notes text)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.enterprise_risks%rowtype;created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.enterprise_risks where id=target_risk_id and status<>'closed';if scoped.id is null or not exists(select 1 from public.audit_control_definitions where id=target_control_id and academy_id=scoped.academy_id and status='active')then raise exception 'active risk and same-academy control required' using errcode='23514';end if;insert into public.risk_control_mappings(risk_id,control_id,reliance,notes,created_by)values(scoped.id,target_control_id,target_reliance,btrim(target_notes),actor)returning id into created_id;perform public.write_audit_event(scoped.academy_id,'risk.control_mapped','enterprise_risk',scoped.id,jsonb_build_object('control_id',target_control_id));return created_id;end;$$;
create function public.record_enterprise_risk_review(target_risk_id uuid,target_inherent_likelihood smallint,target_inherent_impact smallint,target_residual_likelihood smallint,target_residual_impact smallint,target_control_effectiveness text,target_review_notes text,target_evidence_references jsonb,target_next_review_on date)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.enterprise_risks%rowtype;created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.enterprise_risks where id=target_risk_id and status<>'closed'for update;if scoped.id is null or target_next_review_on<=current_date then raise exception 'active risk and future review date required' using errcode='23514';end if;insert into public.enterprise_risk_reviews(risk_id,inherent_likelihood,inherent_impact,residual_likelihood,residual_impact,control_effectiveness,review_notes,evidence_references,reviewed_by)values(scoped.id,target_inherent_likelihood,target_inherent_impact,target_residual_likelihood,target_residual_impact,target_control_effectiveness,btrim(target_review_notes),coalesce(target_evidence_references,'[]'::jsonb),actor)returning id into created_id;update public.enterprise_risks set inherent_likelihood=target_inherent_likelihood,inherent_impact=target_inherent_impact,residual_likelihood=target_residual_likelihood,residual_impact=target_residual_impact,control_effectiveness=target_control_effectiveness,last_reviewed_on=current_date,next_review_on=target_next_review_on,updated_by=actor where id=scoped.id;perform public.write_audit_event(scoped.academy_id,'risk.reviewed','enterprise_risk',scoped.id,jsonb_build_object('review_id',created_id,'next_review_on',target_next_review_on));return created_id;end;$$;
create function public.create_internal_audit_engagement(target_academy_id uuid,target_plan_year smallint,target_risk_id uuid,target_title text,target_objective text,target_scope text,target_priority text,target_lead_user_id uuid,target_planned_start_on date,target_planned_end_on date,target_budget_hours integer)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());created_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;if not exists(select 1 from public.platform_access where user_id=target_lead_user_id and status='active')or(target_risk_id is not null and not exists(select 1 from public.enterprise_risks where id=target_risk_id and academy_id=target_academy_id and status<>'closed'))then raise exception 'active lead and same-academy risk required' using errcode='23514';end if;insert into public.internal_audit_plan_engagements(academy_id,plan_year,risk_id,title,objective,scope,priority,lead_user_id,planned_start_on,planned_end_on,budget_hours,created_by,updated_by)values(target_academy_id,target_plan_year,target_risk_id,btrim(target_title),btrim(target_objective),btrim(target_scope),target_priority,target_lead_user_id,target_planned_start_on,target_planned_end_on,target_budget_hours,actor,actor)returning id into created_id;perform public.write_audit_event(target_academy_id,'audit_plan.engagement_created','internal_audit_engagement',created_id,jsonb_build_object('risk_id',target_risk_id,'plan_year',target_plan_year));return created_id;end;$$;
create function public.update_internal_audit_engagement(target_engagement_id uuid,target_status text,target_actual_hours integer,target_conclusion text)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.internal_audit_plan_engagements%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select*into scoped from public.internal_audit_plan_engagements where id=target_engagement_id for update;if scoped.id is null then raise exception 'open audit engagement required' using errcode='P0002';end if;update public.internal_audit_plan_engagements set status=target_status,actual_hours=target_actual_hours,conclusion=nullif(btrim(coalesce(target_conclusion,'')),''),updated_by=actor where id=scoped.id;perform public.write_audit_event(scoped.academy_id,'audit_plan.engagement_'||target_status,'internal_audit_engagement',scoped.id,jsonb_build_object('actual_hours',target_actual_hours));return true;end;$$;

revoke all on function private.protect_closed_enterprise_risk(),private.protect_risk_review(),private.protect_completed_audit_engagement()from public,anon,authenticated;
revoke all on function public.create_enterprise_risk(uuid,text,text,text,text,text,text,smallint,smallint,smallint,smallint,smallint,uuid),public.update_enterprise_risk(uuid,text,text,smallint,smallint,smallint,uuid,text,date),public.map_risk_control(uuid,uuid,text,text),public.record_enterprise_risk_review(uuid,smallint,smallint,smallint,smallint,text,text,jsonb,date),public.create_internal_audit_engagement(uuid,smallint,uuid,text,text,text,text,uuid,date,date,integer),public.update_internal_audit_engagement(uuid,text,integer,text)from public,anon,authenticated;
grant execute on function public.create_enterprise_risk(uuid,text,text,text,text,text,text,smallint,smallint,smallint,smallint,smallint,uuid),public.update_enterprise_risk(uuid,text,text,smallint,smallint,smallint,uuid,text,date),public.map_risk_control(uuid,uuid,text,text),public.record_enterprise_risk_review(uuid,smallint,smallint,smallint,smallint,text,text,jsonb,date),public.create_internal_audit_engagement(uuid,smallint,uuid,text,text,text,text,uuid,date,date,integer),public.update_internal_audit_engagement(uuid,text,integer,text)to authenticated;

commit;
