begin;

create table public.consolidation_groups(
 id uuid primary key default gen_random_uuid(),name text not null,reporting_currency text not null,lead_academy_id uuid not null references public.academies(id) on delete restrict,
 active boolean not null default true,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint consolidation_group_name_length check(char_length(name) between 2 and 120),constraint consolidation_group_currency check(reporting_currency~'^[A-Z]{3}$')
);
create table public.consolidation_group_members(
 id uuid primary key default gen_random_uuid(),group_id uuid not null references public.consolidation_groups(id) on delete restrict,academy_id uuid not null references public.academies(id) on delete restrict,
 functional_currency text not null,ownership_bps integer not null default 10000,active boolean not null default true,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),
 constraint consolidation_member_currency check(functional_currency~'^[A-Z]{3}$'),constraint consolidation_member_ownership check(ownership_bps between 1 and 10000),unique(group_id,academy_id)
);
create table public.consolidation_fx_rates(
 id uuid primary key default gen_random_uuid(),group_id uuid not null references public.consolidation_groups(id) on delete restrict,currency text not null,rate_date date not null,
 rate_to_reporting numeric(20,8) not null,rate_type text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint consolidation_fx_currency check(currency~'^[A-Z]{3}$'),constraint consolidation_fx_positive check(rate_to_reporting>0 and rate_to_reporting<1000000),constraint consolidation_fx_type check(rate_type in('average','closing')),unique(group_id,currency,rate_date,rate_type)
);
create table public.intercompany_eliminations(
 id uuid primary key default gen_random_uuid(),group_id uuid not null references public.consolidation_groups(id) on delete restrict,period_starts_on date not null,period_ends_on date not null,
 from_academy_id uuid not null references public.academies(id) on delete restrict,to_academy_id uuid not null references public.academies(id) on delete restrict,category text not null,amount_minor bigint not null,
 description text not null,status text not null default 'draft',created_by uuid not null references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint consolidation_elimination_period check(period_ends_on>=period_starts_on),constraint consolidation_elimination_parties check(from_academy_id<>to_academy_id),constraint consolidation_elimination_category check(category in('asset','liability','equity','revenue','expense')),constraint consolidation_elimination_amount check(amount_minor>0),constraint consolidation_elimination_description check(char_length(description) between 2 and 300),constraint consolidation_elimination_status check(status in('draft','approved')),constraint consolidation_elimination_approval check((status='draft' and approved_by is null and approved_at is null)or(status='approved' and approved_by is not null and approved_at is not null))
);
create table public.consolidation_snapshots(
 id uuid primary key default gen_random_uuid(),group_id uuid not null references public.consolidation_groups(id) on delete restrict,period_starts_on date not null,period_ends_on date not null,reporting_currency text not null,
 status text not null default 'draft',revenue_minor bigint not null default 0,expense_minor bigint not null default 0,net_income_minor bigint not null default 0,asset_minor bigint not null default 0,liability_minor bigint not null default 0,equity_minor bigint not null default 0,
 elimination_minor bigint not null default 0,missing_fx_rates integer not null default 0,academy_breakdown jsonb not null default '[]'::jsonb,generated_by uuid not null references auth.users(id),generated_at timestamptz not null default now(),locked_by uuid references auth.users(id),locked_at timestamptz,
 constraint consolidation_snapshot_period check(period_ends_on>=period_starts_on),constraint consolidation_snapshot_currency check(reporting_currency~'^[A-Z]{3}$'),constraint consolidation_snapshot_status check(status in('draft','locked')),constraint consolidation_snapshot_lock check((status='draft' and locked_by is null and locked_at is null)or(status='locked' and locked_by is not null and locked_at is not null)),unique(group_id,period_starts_on,period_ends_on)
);

create index consolidation_members_group_idx on public.consolidation_group_members(group_id,active);create index consolidation_members_academy_idx on public.consolidation_group_members(academy_id);create index consolidation_fx_lookup_idx on public.consolidation_fx_rates(group_id,currency,rate_type,rate_date desc);create index consolidation_eliminations_period_idx on public.intercompany_eliminations(group_id,period_ends_on,status);create index consolidation_snapshots_period_idx on public.consolidation_snapshots(group_id,period_ends_on desc);

alter table public.consolidation_groups enable row level security;alter table public.consolidation_group_members enable row level security;alter table public.consolidation_fx_rates enable row level security;alter table public.intercompany_eliminations enable row level security;alter table public.consolidation_snapshots enable row level security;
revoke all on public.consolidation_groups,public.consolidation_group_members,public.consolidation_fx_rates,public.intercompany_eliminations,public.consolidation_snapshots from public,anon,authenticated;
grant select,insert,update on public.consolidation_groups,public.consolidation_group_members,public.consolidation_fx_rates,public.intercompany_eliminations,public.consolidation_snapshots to authenticated;
grant select,insert,update,delete on public.consolidation_groups,public.consolidation_group_members,public.consolidation_fx_rates,public.intercompany_eliminations,public.consolidation_snapshots to service_role;
create policy consolidation_groups_read_administrators on public.consolidation_groups for select to authenticated using((select private.is_platform_administrator()));create policy consolidation_groups_insert_administrators on public.consolidation_groups for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));create policy consolidation_groups_update_administrators on public.consolidation_groups for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy consolidation_members_read_administrators on public.consolidation_group_members for select to authenticated using((select private.is_platform_administrator()));create policy consolidation_members_insert_administrators on public.consolidation_group_members for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));create policy consolidation_members_update_administrators on public.consolidation_group_members for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy consolidation_fx_read_administrators on public.consolidation_fx_rates for select to authenticated using((select private.is_platform_administrator()));create policy consolidation_fx_insert_administrators on public.consolidation_fx_rates for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));create policy consolidation_fx_update_administrators on public.consolidation_fx_rates for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy consolidation_eliminations_read_administrators on public.intercompany_eliminations for select to authenticated using((select private.is_platform_administrator()));create policy consolidation_eliminations_insert_administrators on public.intercompany_eliminations for insert to authenticated with check((select private.is_platform_administrator()) and created_by=(select auth.uid()));create policy consolidation_eliminations_update_administrators on public.intercompany_eliminations for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));
create policy consolidation_snapshots_read_administrators on public.consolidation_snapshots for select to authenticated using((select private.is_platform_administrator()));create policy consolidation_snapshots_insert_administrators on public.consolidation_snapshots for insert to authenticated with check((select private.is_platform_administrator()) and generated_by=(select auth.uid()));create policy consolidation_snapshots_update_administrators on public.consolidation_snapshots for update to authenticated using((select private.is_platform_administrator())) with check((select private.is_platform_administrator()));

create function private.protect_locked_consolidation_snapshot()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status='locked' then raise exception 'locked consolidation snapshot is immutable' using errcode='23514';end if;return new;end;$$;
create trigger protect_locked_consolidation_snapshot before update or delete on public.consolidation_snapshots for each row execute function private.protect_locked_consolidation_snapshot();

create function public.create_consolidation_group(target_name text,target_reporting_currency text,target_lead_academy_id uuid)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());new_id uuid;currency text:=upper(btrim(target_reporting_currency));begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;if char_length(btrim(target_name))not between 2 and 120 or currency!~'^[A-Z]{3}$' or not exists(select 1 from public.academies where id=target_lead_academy_id)then raise exception 'invalid consolidation group' using errcode='22023';end if;insert into public.consolidation_groups(name,reporting_currency,lead_academy_id,created_by)values(btrim(target_name),currency,target_lead_academy_id,actor)returning id into new_id;insert into public.consolidation_group_members(group_id,academy_id,functional_currency,created_by)values(new_id,target_lead_academy_id,currency,actor);perform public.write_audit_event(target_lead_academy_id,'consolidation.group_created','consolidation_group',new_id,jsonb_build_object('reporting_currency',currency));return new_id;end;$$;
create function public.add_consolidation_member(target_group_id uuid,target_academy_id uuid,target_functional_currency text,target_ownership_bps integer default 10000)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());lead_id uuid;new_id uuid;currency text:=upper(btrim(target_functional_currency));begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select lead_academy_id into lead_id from public.consolidation_groups where id=target_group_id and active;if lead_id is null or not exists(select 1 from public.academies where id=target_academy_id)or currency!~'^[A-Z]{3}$' or target_ownership_bps not between 1 and 10000 then raise exception 'invalid consolidation member' using errcode='22023';end if;insert into public.consolidation_group_members(group_id,academy_id,functional_currency,ownership_bps,created_by)values(target_group_id,target_academy_id,currency,target_ownership_bps,actor)on conflict(group_id,academy_id)do update set functional_currency=excluded.functional_currency,ownership_bps=excluded.ownership_bps,active=true returning id into new_id;perform public.write_audit_event(lead_id,'consolidation.member_saved','consolidation_group_member',new_id,jsonb_build_object('academy_id',target_academy_id,'functional_currency',currency,'ownership_bps',target_ownership_bps));return new_id;end;$$;
create function public.save_consolidation_fx_rate(target_group_id uuid,target_currency text,target_rate_date date,target_rate_type text,target_rate_to_reporting numeric)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());lead_id uuid;new_id uuid;currency text:=upper(btrim(target_currency));begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select lead_academy_id into lead_id from public.consolidation_groups where id=target_group_id and active;if lead_id is null or currency!~'^[A-Z]{3}$' or target_rate_type not in('average','closing')or target_rate_to_reporting<=0 or target_rate_to_reporting>=1000000 then raise exception 'invalid consolidation FX rate' using errcode='22023';end if;insert into public.consolidation_fx_rates(group_id,currency,rate_date,rate_type,rate_to_reporting,created_by)values(target_group_id,currency,target_rate_date,target_rate_type,target_rate_to_reporting,actor)on conflict(group_id,currency,rate_date,rate_type)do update set rate_to_reporting=excluded.rate_to_reporting,updated_at=now()returning id into new_id;perform public.write_audit_event(lead_id,'consolidation.fx_rate_saved','consolidation_fx_rate',new_id,jsonb_build_object('currency',currency,'rate_type',target_rate_type,'rate_date',target_rate_date));return new_id;end;$$;
create function public.record_intercompany_elimination(target_group_id uuid,target_period_starts_on date,target_period_ends_on date,target_from_academy_id uuid,target_to_academy_id uuid,target_category text,target_amount_minor bigint,target_description text)returns uuid language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());lead_id uuid;new_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select lead_academy_id into lead_id from public.consolidation_groups where id=target_group_id and active;if lead_id is null or target_period_ends_on<target_period_starts_on or target_from_academy_id=target_to_academy_id or target_category not in('asset','liability','equity','revenue','expense')or target_amount_minor<=0 or char_length(btrim(target_description))not between 2 and 300 or not exists(select 1 from public.consolidation_group_members where group_id=target_group_id and academy_id=target_from_academy_id and active)or not exists(select 1 from public.consolidation_group_members where group_id=target_group_id and academy_id=target_to_academy_id and active)then raise exception 'invalid intercompany elimination' using errcode='22023';end if;insert into public.intercompany_eliminations(group_id,period_starts_on,period_ends_on,from_academy_id,to_academy_id,category,amount_minor,description,created_by)values(target_group_id,target_period_starts_on,target_period_ends_on,target_from_academy_id,target_to_academy_id,target_category,target_amount_minor,btrim(target_description),actor)returning id into new_id;perform public.write_audit_event(lead_id,'consolidation.elimination_recorded','intercompany_elimination',new_id,jsonb_build_object('category',target_category,'amount_minor',target_amount_minor));return new_id;end;$$;
create function public.approve_intercompany_elimination(target_elimination_id uuid)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());lead_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select g.lead_academy_id into lead_id from public.intercompany_eliminations e join public.consolidation_groups g on g.id=e.group_id where e.id=target_elimination_id and e.status='draft' for update of e;if lead_id is null then raise exception 'draft elimination required' using errcode='23514';end if;update public.intercompany_eliminations set status='approved',approved_by=actor,approved_at=now(),updated_at=now()where id=target_elimination_id;perform public.write_audit_event(lead_id,'consolidation.elimination_approved','intercompany_elimination',target_elimination_id,'{}'::jsonb);return true;end;$$;

create function public.generate_consolidation_snapshot(target_group_id uuid,target_period_starts_on date,target_period_ends_on date)returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());g public.consolidation_groups%rowtype;snapshot_id uuid;revenue bigint:=0;expense bigint:=0;asset bigint:=0;liability bigint:=0;equity bigint:=0;elim_revenue bigint:=0;elim_expense bigint:=0;elim_asset bigint:=0;elim_liability bigint:=0;elim_equity bigint:=0;missing integer:=0;breakdown jsonb:='[]'::jsonb;
begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into g from public.consolidation_groups where id=target_group_id and active for update;if g.id is null or target_period_ends_on<target_period_starts_on or target_period_ends_on-target_period_starts_on>1096 then raise exception 'invalid consolidation period' using errcode='22023';end if;if exists(select 1 from public.consolidation_snapshots where group_id=target_group_id and period_starts_on=target_period_starts_on and period_ends_on=target_period_ends_on and status='locked')then raise exception 'locked consolidation snapshot is immutable' using errcode='23514';end if;
 select count(*) into missing from public.consolidation_group_members m where m.group_id=target_group_id and m.active and m.functional_currency<>g.reporting_currency and(not exists(select 1 from public.consolidation_fx_rates r where r.group_id=g.id and r.currency=m.functional_currency and r.rate_type='average' and r.rate_date<=target_period_ends_on)or not exists(select 1 from public.consolidation_fx_rates r where r.group_id=g.id and r.currency=m.functional_currency and r.rate_type='closing' and r.rate_date<=target_period_ends_on));
 with member_rates as(select m.academy_id,m.functional_currency,m.ownership_bps,case when m.functional_currency=g.reporting_currency then 1::numeric else(select r.rate_to_reporting from public.consolidation_fx_rates r where r.group_id=g.id and r.currency=m.functional_currency and r.rate_type='average' and r.rate_date<=target_period_ends_on order by r.rate_date desc limit 1)end average_rate,case when m.functional_currency=g.reporting_currency then 1::numeric else(select r.rate_to_reporting from public.consolidation_fx_rates r where r.group_id=g.id and r.currency=m.functional_currency and r.rate_type='closing' and r.rate_date<=target_period_ends_on order by r.rate_date desc limit 1)end closing_rate from public.consolidation_group_members m where m.group_id=g.id and m.active),academy_totals as(select a.id academy_id,a.name,m.functional_currency,m.ownership_bps,coalesce(sum(case when account.category='revenue' and entry.entry_date between target_period_starts_on and target_period_ends_on then round((line.credit_minor-line.debit_minor)*m.average_rate*m.ownership_bps/10000.0)::bigint else 0 end),0) revenue_minor,coalesce(sum(case when account.category='expense' and entry.entry_date between target_period_starts_on and target_period_ends_on then round((line.debit_minor-line.credit_minor)*m.average_rate*m.ownership_bps/10000.0)::bigint else 0 end),0) expense_minor,coalesce(sum(case when account.category='asset' and entry.entry_date<=target_period_ends_on then round((line.debit_minor-line.credit_minor)*m.closing_rate*m.ownership_bps/10000.0)::bigint else 0 end),0) asset_minor,coalesce(sum(case when account.category='liability' and entry.entry_date<=target_period_ends_on then round((line.credit_minor-line.debit_minor)*m.closing_rate*m.ownership_bps/10000.0)::bigint else 0 end),0) liability_minor,coalesce(sum(case when account.category='equity' and entry.entry_date<=target_period_ends_on then round((line.credit_minor-line.debit_minor)*m.closing_rate*m.ownership_bps/10000.0)::bigint else 0 end),0) equity_minor from member_rates m join public.academies a on a.id=m.academy_id left join public.gl_journal_entries entry on entry.academy_id=m.academy_id and entry.currency=m.functional_currency and entry.status in('posted','reversed') and entry.entry_date<=target_period_ends_on left join public.gl_journal_lines line on line.journal_entry_id=entry.id left join public.gl_accounts account on account.id=line.account_id group by a.id,a.name,m.functional_currency,m.ownership_bps)
 select coalesce(sum(revenue_minor),0),coalesce(sum(expense_minor),0),coalesce(sum(asset_minor),0),coalesce(sum(liability_minor),0),coalesce(sum(equity_minor),0),coalesce(jsonb_agg(jsonb_build_object('academy_id',academy_id,'academy_name',name,'functional_currency',functional_currency,'ownership_bps',ownership_bps,'revenue_minor',revenue_minor,'expense_minor',expense_minor,'net_income_minor',revenue_minor-expense_minor,'asset_minor',asset_minor,'liability_minor',liability_minor,'equity_minor',equity_minor)order by name),'[]'::jsonb) into revenue,expense,asset,liability,equity,breakdown from academy_totals;
 select coalesce(sum(amount_minor)filter(where category='revenue'),0),coalesce(sum(amount_minor)filter(where category='expense'),0),coalesce(sum(amount_minor)filter(where category='asset'),0),coalesce(sum(amount_minor)filter(where category='liability'),0),coalesce(sum(amount_minor)filter(where category='equity'),0)into elim_revenue,elim_expense,elim_asset,elim_liability,elim_equity from public.intercompany_eliminations where group_id=g.id and period_starts_on=target_period_starts_on and period_ends_on=target_period_ends_on and status='approved';
 insert into public.consolidation_snapshots(group_id,period_starts_on,period_ends_on,reporting_currency,revenue_minor,expense_minor,net_income_minor,asset_minor,liability_minor,equity_minor,elimination_minor,missing_fx_rates,academy_breakdown,generated_by)values(g.id,target_period_starts_on,target_period_ends_on,g.reporting_currency,revenue-elim_revenue,expense-elim_expense,(revenue-elim_revenue)-(expense-elim_expense),asset-elim_asset,liability-elim_liability,equity-elim_equity,elim_revenue+elim_expense+elim_asset+elim_liability+elim_equity,missing,breakdown,actor)on conflict(group_id,period_starts_on,period_ends_on)do update set reporting_currency=excluded.reporting_currency,revenue_minor=excluded.revenue_minor,expense_minor=excluded.expense_minor,net_income_minor=excluded.net_income_minor,asset_minor=excluded.asset_minor,liability_minor=excluded.liability_minor,equity_minor=excluded.equity_minor,elimination_minor=excluded.elimination_minor,missing_fx_rates=excluded.missing_fx_rates,academy_breakdown=excluded.academy_breakdown,generated_by=actor,generated_at=now()returning id into snapshot_id;perform public.write_audit_event(g.lead_academy_id,'consolidation.snapshot_generated','consolidation_snapshot',snapshot_id,jsonb_build_object('period_starts_on',target_period_starts_on,'period_ends_on',target_period_ends_on,'missing_fx_rates',missing));return snapshot_id;end;$$;
create function public.lock_consolidation_snapshot(target_snapshot_id uuid)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.consolidation_snapshots%rowtype;lead_id uuid;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into scoped from public.consolidation_snapshots where id=target_snapshot_id and status='draft' for update;select lead_academy_id into lead_id from public.consolidation_groups where id=scoped.group_id;if scoped.id is null then raise exception 'draft consolidation snapshot required' using errcode='23514';end if;if scoped.missing_fx_rates>0 then raise exception 'missing FX rates prevent consolidation lock' using errcode='23514';end if;if exists(select 1 from public.intercompany_eliminations where group_id=scoped.group_id and period_starts_on=scoped.period_starts_on and period_ends_on=scoped.period_ends_on and status='draft')then raise exception 'unapproved eliminations prevent consolidation lock' using errcode='23514';end if;update public.consolidation_snapshots set status='locked',locked_by=actor,locked_at=now()where id=scoped.id;perform public.write_audit_event(lead_id,'consolidation.snapshot_locked','consolidation_snapshot',scoped.id,jsonb_build_object('period_starts_on',scoped.period_starts_on,'period_ends_on',scoped.period_ends_on));return true;end;$$;

revoke all on function private.protect_locked_consolidation_snapshot() from public,anon,authenticated;
revoke all on function public.create_consolidation_group(text,text,uuid),public.add_consolidation_member(uuid,uuid,text,integer),public.save_consolidation_fx_rate(uuid,text,date,text,numeric),public.record_intercompany_elimination(uuid,date,date,uuid,uuid,text,bigint,text),public.approve_intercompany_elimination(uuid),public.generate_consolidation_snapshot(uuid,date,date),public.lock_consolidation_snapshot(uuid) from public,anon,authenticated;
grant execute on function public.create_consolidation_group(text,text,uuid),public.add_consolidation_member(uuid,uuid,text,integer),public.save_consolidation_fx_rate(uuid,text,date,text,numeric),public.record_intercompany_elimination(uuid,date,date,uuid,uuid,text,bigint,text),public.approve_intercompany_elimination(uuid),public.generate_consolidation_snapshot(uuid,date,date),public.lock_consolidation_snapshot(uuid) to authenticated;

commit;
