begin;

create table public.management_report_packs(
 id uuid primary key default gen_random_uuid(),consolidation_snapshot_id uuid not null unique references public.consolidation_snapshots(id) on delete restrict,group_id uuid not null references public.consolidation_groups(id) on delete restrict,lead_academy_id uuid not null references public.academies(id) on delete restrict,
 period_starts_on date not null,period_ends_on date not null,reporting_currency text not null,status text not null default 'draft',
 revenue_minor bigint not null default 0,expense_minor bigint not null default 0,net_income_minor bigint not null default 0,assets_minor bigint not null default 0,liabilities_minor bigint not null default 0,equity_minor bigint not null default 0,
 revenue_budget_minor bigint not null default 0,expense_budget_minor bigint not null default 0,revenue_variance_minor bigint not null default 0,expense_variance_minor bigint not null default 0,
 cash_balance_minor bigint not null default 0,receivables_minor bigint not null default 0,payables_minor bigint not null default 0,net_working_capital_minor bigint not null default 0,vat_payable_minor bigint not null default 0,
 overdue_invoice_count integer not null default 0,escalated_collection_count integer not null default 0,data_quality_warnings integer not null default 0,academy_breakdown jsonb not null default '[]'::jsonb,source_snapshot jsonb not null default '{}'::jsonb,
 executive_summary text,finance_commentary text,key_risks text,outlook text,generated_by uuid not null references auth.users(id),generated_at timestamptz not null default now(),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),locked_by uuid references auth.users(id),locked_at timestamptz,
 constraint management_pack_period check(period_ends_on>=period_starts_on),constraint management_pack_currency check(reporting_currency~'^[A-Z]{3}$'),constraint management_pack_status check(status in('draft','locked')),constraint management_pack_lock_state check((status='draft' and locked_by is null and locked_at is null)or(status='locked' and locked_by is not null and locked_at is not null)),constraint management_pack_comment_lengths check((executive_summary is null or char_length(executive_summary)between 10 and 4000)and(finance_commentary is null or char_length(finance_commentary)between 10 and 4000)and(key_risks is null or char_length(key_risks)between 10 and 4000)and(outlook is null or char_length(outlook)between 10 and 4000))
);
create index management_packs_group_period_idx on public.management_report_packs(group_id,period_ends_on desc);create index management_packs_lead_academy_idx on public.management_report_packs(lead_academy_id);create index management_packs_generated_by_idx on public.management_report_packs(generated_by);create index management_packs_locked_by_idx on public.management_report_packs(locked_by)where locked_by is not null;
alter table public.management_report_packs enable row level security;
revoke all on public.management_report_packs from public,anon,authenticated;grant select,insert,update on public.management_report_packs to authenticated;grant select,insert,update,delete on public.management_report_packs to service_role;
create policy management_packs_read_administrators on public.management_report_packs for select to authenticated using((select private.is_platform_administrator()));create policy management_packs_insert_administrators on public.management_report_packs for insert to authenticated with check((select private.is_platform_administrator())and generated_by=(select auth.uid())and updated_by=(select auth.uid()));create policy management_packs_update_administrators on public.management_report_packs for update to authenticated using((select private.is_platform_administrator()))with check((select private.is_platform_administrator())and updated_by=(select auth.uid()));

create function private.protect_locked_management_report_pack()returns trigger language plpgsql security invoker set search_path='' as $$begin if old.status='locked' then raise exception 'locked management report pack is immutable' using errcode='23514';end if;new.updated_at:=now();return new;end;$$;
create trigger protect_locked_management_report_pack before update or delete on public.management_report_packs for each row execute function private.protect_locked_management_report_pack();

create function public.generate_management_report_pack(target_consolidation_snapshot_id uuid)returns uuid language plpgsql security invoker set search_path='' as $$
declare actor uuid:=(select auth.uid());snap public.consolidation_snapshots%rowtype;lead_id uuid;pack_id uuid;budget_revenue bigint:=0;budget_expense bigint:=0;cash_balance bigint:=0;receivables bigint:=0;payables bigint:=0;vat_payable bigint:=0;overdue_count integer:=0;escalated_count integer:=0;warnings integer:=0;
begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into snap from public.consolidation_snapshots where id=target_consolidation_snapshot_id and status='locked';if snap.id is null then raise exception 'locked consolidation snapshot required' using errcode='23514';end if;select lead_academy_id into lead_id from public.consolidation_groups where id=snap.group_id;if exists(select 1 from public.management_report_packs where consolidation_snapshot_id=snap.id and status='locked')then raise exception 'locked management report pack is immutable' using errcode='23514';end if;
 with rates as(select m.academy_id,m.functional_currency,m.ownership_bps,case when m.functional_currency=snap.reporting_currency then 1::numeric else(select rate_to_reporting from public.consolidation_fx_rates r where r.group_id=snap.group_id and r.currency=m.functional_currency and r.rate_type='average' and r.rate_date<=snap.period_ends_on order by r.rate_date desc limit 1)end average_rate,case when m.functional_currency=snap.reporting_currency then 1::numeric else(select rate_to_reporting from public.consolidation_fx_rates r where r.group_id=snap.group_id and r.currency=m.functional_currency and r.rate_type='closing' and r.rate_date<=snap.period_ends_on order by r.rate_date desc limit 1)end closing_rate from public.consolidation_group_members m where m.group_id=snap.group_id and m.active),budget as(select account.category,sum(round(line.budget_minor*r.average_rate*r.ownership_bps/10000.0))::bigint amount from rates r join public.financial_budget_plans plan on plan.academy_id=r.academy_id and plan.fiscal_year=extract(year from snap.period_ends_on)::integer and plan.currency=r.functional_currency and plan.status='approved' join public.financial_budget_lines line on line.plan_id=plan.id and line.month_start between date_trunc('month',snap.period_starts_on)::date and date_trunc('month',snap.period_ends_on)::date join public.gl_accounts account on account.id=line.account_id group by account.category),liquidity as(select r.academy_id,r.closing_rate,r.ownership_bps,coalesce((select amount_minor from public.treasury_opening_balances t where t.academy_id=r.academy_id and t.currency=r.functional_currency and t.as_of_date<=snap.period_ends_on order by t.as_of_date desc limit 1),0)cash_minor from rates r),ar as(select coalesce(sum(round(invoice.amount_minor*r.closing_rate*r.ownership_bps/10000.0)),0)::bigint amount,count(*)filter(where invoice.due_at::date<snap.period_ends_on)::integer overdue from rates r join public.invoices invoice on invoice.academy_id=r.academy_id and invoice.currency=r.functional_currency and invoice.status in('issued','overdue')),ap as(select coalesce(sum(round(fin.amount_minor*r.closing_rate*r.ownership_bps/10000.0)),0)::bigint amount from rates r join public.supplier_invoices invoice on invoice.academy_id=r.academy_id and invoice.status='approved' join public.supplier_invoice_financials fin on fin.invoice_id=invoice.id and fin.currency=r.functional_currency),tax as(select coalesce(sum(round(v.net_vat_minor*r.closing_rate*r.ownership_bps/10000.0)),0)::bigint amount from rates r join public.vat_returns v on v.academy_id=r.academy_id and v.currency=r.functional_currency and v.status='submitted' and v.period_ends_on between snap.period_starts_on and snap.period_ends_on)
 select coalesce((select amount from budget where category='revenue'),0),coalesce((select amount from budget where category='expense'),0),coalesce((select sum(round(cash_minor*closing_rate*ownership_bps/10000.0))::bigint from liquidity),0),coalesce((select amount from ar),0),coalesce((select overdue from ar),0),coalesce((select amount from ap),0),coalesce((select amount from tax),0)into budget_revenue,budget_expense,cash_balance,receivables,overdue_count,payables,vat_payable;
 select count(*) into escalated_count from public.receivable_collection_cases c join public.consolidation_group_members m on m.academy_id=c.academy_id and m.group_id=snap.group_id and m.active where c.status='escalated';select count(*) into warnings from public.consolidation_group_members m where m.group_id=snap.group_id and m.active and not exists(select 1 from public.financial_budget_plans p where p.academy_id=m.academy_id and p.fiscal_year=extract(year from snap.period_ends_on)::integer and p.currency=m.functional_currency and p.status='approved');
 insert into public.management_report_packs(consolidation_snapshot_id,group_id,lead_academy_id,period_starts_on,period_ends_on,reporting_currency,revenue_minor,expense_minor,net_income_minor,assets_minor,liabilities_minor,equity_minor,revenue_budget_minor,expense_budget_minor,revenue_variance_minor,expense_variance_minor,cash_balance_minor,receivables_minor,payables_minor,net_working_capital_minor,vat_payable_minor,overdue_invoice_count,escalated_collection_count,data_quality_warnings,academy_breakdown,source_snapshot,generated_by,updated_by)values(snap.id,snap.group_id,lead_id,snap.period_starts_on,snap.period_ends_on,snap.reporting_currency,snap.revenue_minor,snap.expense_minor,snap.net_income_minor,snap.asset_minor,snap.liability_minor,snap.equity_minor,budget_revenue,budget_expense,snap.revenue_minor-budget_revenue,budget_expense-snap.expense_minor,cash_balance,receivables,payables,receivables-payables,vat_payable,overdue_count,escalated_count,warnings,snap.academy_breakdown,jsonb_build_object('consolidation_snapshot_id',snap.id,'consolidation_locked_at',snap.locked_at,'elimination_minor',snap.elimination_minor,'generated_at',now()),actor,actor)on conflict(consolidation_snapshot_id)do update set revenue_minor=excluded.revenue_minor,expense_minor=excluded.expense_minor,net_income_minor=excluded.net_income_minor,assets_minor=excluded.assets_minor,liabilities_minor=excluded.liabilities_minor,equity_minor=excluded.equity_minor,revenue_budget_minor=excluded.revenue_budget_minor,expense_budget_minor=excluded.expense_budget_minor,revenue_variance_minor=excluded.revenue_variance_minor,expense_variance_minor=excluded.expense_variance_minor,cash_balance_minor=excluded.cash_balance_minor,receivables_minor=excluded.receivables_minor,payables_minor=excluded.payables_minor,net_working_capital_minor=excluded.net_working_capital_minor,vat_payable_minor=excluded.vat_payable_minor,overdue_invoice_count=excluded.overdue_invoice_count,escalated_collection_count=excluded.escalated_collection_count,data_quality_warnings=excluded.data_quality_warnings,academy_breakdown=excluded.academy_breakdown,source_snapshot=excluded.source_snapshot,generated_by=actor,updated_by=actor,generated_at=now(),updated_at=now()returning id into pack_id;perform public.write_audit_event(lead_id,'management_reporting.pack_generated','management_report_pack',pack_id,jsonb_build_object('consolidation_snapshot_id',snap.id,'data_quality_warnings',warnings));return pack_id;end;$$;

create function public.save_management_report_commentary(target_pack_id uuid,target_executive_summary text,target_finance_commentary text,target_key_risks text,target_outlook text)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.management_report_packs%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into scoped from public.management_report_packs where id=target_pack_id and status='draft' for update;if scoped.id is null then raise exception 'draft management report pack required' using errcode='23514';end if;if char_length(btrim(target_executive_summary))not between 10 and 4000 or char_length(btrim(target_finance_commentary))not between 10 and 4000 or char_length(btrim(target_key_risks))not between 10 and 4000 or char_length(btrim(target_outlook))not between 10 and 4000 then raise exception 'complete management commentary required' using errcode='22023';end if;update public.management_report_packs set executive_summary=btrim(target_executive_summary),finance_commentary=btrim(target_finance_commentary),key_risks=btrim(target_key_risks),outlook=btrim(target_outlook),updated_by=actor,updated_at=now()where id=scoped.id;perform public.write_audit_event(scoped.lead_academy_id,'management_reporting.commentary_saved','management_report_pack',scoped.id,'{}'::jsonb);return true;end;$$;
create function public.lock_management_report_pack(target_pack_id uuid)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.management_report_packs%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into scoped from public.management_report_packs where id=target_pack_id and status='draft' for update;if scoped.id is null then raise exception 'draft management report pack required' using errcode='23514';end if;if scoped.executive_summary is null or scoped.finance_commentary is null or scoped.key_risks is null or scoped.outlook is null then raise exception 'complete management commentary before locking' using errcode='23514';end if;if not exists(select 1 from public.consolidation_snapshots where id=scoped.consolidation_snapshot_id and status='locked')then raise exception 'locked consolidation snapshot required' using errcode='23514';end if;update public.management_report_packs set status='locked',locked_by=actor,locked_at=now(),updated_by=actor,updated_at=now()where id=scoped.id;perform public.write_audit_event(scoped.lead_academy_id,'management_reporting.pack_locked','management_report_pack',scoped.id,jsonb_build_object('period_starts_on',scoped.period_starts_on,'period_ends_on',scoped.period_ends_on));return true;end;$$;
create function public.record_management_report_export(target_pack_id uuid)returns boolean language plpgsql security invoker set search_path='' as $$declare actor uuid:=(select auth.uid());scoped public.management_report_packs%rowtype;begin if actor is null or not private.is_platform_administrator()then raise exception 'platform administrator access required' using errcode='42501';end if;select * into scoped from public.management_report_packs where id=target_pack_id;if scoped.id is null then raise exception 'management report pack not found' using errcode='P0002';end if;perform public.write_audit_event(scoped.lead_academy_id,'management_reporting.pack_exported','management_report_pack',scoped.id,jsonb_build_object('status',scoped.status));return true;end;$$;

revoke all on function private.protect_locked_management_report_pack()from public,anon,authenticated;revoke all on function public.generate_management_report_pack(uuid),public.save_management_report_commentary(uuid,text,text,text,text),public.lock_management_report_pack(uuid),public.record_management_report_export(uuid)from public,anon,authenticated;grant execute on function public.generate_management_report_pack(uuid),public.save_management_report_commentary(uuid,text,text,text,text),public.lock_management_report_pack(uuid),public.record_management_report_export(uuid)to authenticated;
commit;
