-- Rollback for Batch 6 Staff, Arena & Academy Operations.
begin;
drop function if exists public.upsert_academy_commission_calculation(uuid, uuid, uuid, date, date, text, numeric, numeric, numeric, text, text, text, text);
drop function if exists public.upsert_academy_payroll_calculation(uuid, uuid, uuid, date, date, text, numeric, numeric, numeric, text, text, text, text);
drop function if exists public.approve_academy_commission_calculation(uuid, uuid);
drop function if exists public.approve_academy_payroll_calculation(uuid, uuid);
drop function if exists public.upsert_academy_lesson_capacity(uuid, uuid, integer, integer, integer, text, text, text);
drop function if exists public.upsert_academy_resource_booking(uuid, uuid, uuid, uuid, uuid, text, timestamptz, timestamptz, text, text);
drop function if exists public.upsert_academy_resource(uuid, uuid, text, text, text, integer, boolean, text, text);
drop function if exists public.upsert_academy_staff_shift(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text, text);
drop function if exists public.upsert_academy_staff_availability(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text);
drop function if exists public.upsert_academy_staff_leave(uuid, uuid, uuid, text, timestamptz, timestamptz, text, text);
drop function if exists public.upsert_academy_coach_allocation(uuid, uuid, uuid, uuid, timestamptz, timestamptz, text, text, text);
drop function if exists public.upsert_academy_staff_profile(uuid, uuid, uuid, text, text, text, boolean, text);
drop function if exists public.upsert_academy_facility_inspection(uuid, uuid, uuid, text, timestamptz, text, text, text, text, text, timestamptz, text);
drop function if exists public.upsert_academy_maintenance_work_order(uuid, uuid, uuid, uuid, text, text, text, text, text, text, timestamptz, text);
drop function if exists public.create_academy_operations_alert(uuid, text, text, text, text, text, text, text, uuid, timestamptz);
drop function if exists public.get_academy_operations_workspace(uuid);
drop function if exists public.get_academy_operations_access(uuid);
drop function if exists private.audit_academy_operations(uuid, text, uuid, text, jsonb, jsonb);
drop function if exists private.lock_academy_staff_schedule(uuid, uuid);
drop function if exists private.assert_academy_operation_record_organization(uuid, text, uuid);
drop function if exists private.assert_academy_compensation_access(uuid);
drop function if exists private.assert_academy_operations_access(uuid);
drop function if exists private.can_view_academy_compensation(uuid);
drop function if exists private.can_manage_academy_operations(uuid);
drop function if exists private.academy_operations_enabled(uuid);
drop table if exists public.academy_operations_audit_events;
drop table if exists public.academy_commission_calculations;
drop table if exists public.academy_payroll_calculations;
drop table if exists public.academy_operations_alerts;
drop table if exists public.academy_maintenance_work_orders;
drop table if exists public.academy_facility_inspections;
drop table if exists public.academy_lesson_capacity_controls;
drop table if exists public.academy_resource_bookings;
drop table if exists public.academy_resources;
drop table if exists public.academy_coach_allocations;
drop table if exists public.academy_staff_leave;
drop table if exists public.academy_staff_shifts;
drop table if exists public.academy_staff_availability;
drop table if exists public.academy_staff_profiles;
drop table if exists public.academy_operations_feature_flags;
commit;